// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$30 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$30() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(Discord_Client_GetDiscordClientConnectedUserCallback.class, "apply", constants$29.const$5);
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        constants$29.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(Discord_Client_RelationshipGroupsUpdatedCallback.class, "apply", constants$11.const$0);
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(Discord_Client_UserUpdatedCallback.class, "apply", constants$11.const$0);
    static final StructLayout const$4 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("opaque")
    ).withName("Discord_ActivityInvite");
    static final VarHandle const$5 = constants$30.const$4.varHandle(MemoryLayout.PathElement.groupElement("opaque"));
}


