// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$62 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$62() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "Discord_DeviceAuthorizationArgs_SetScopes",
        constants$34.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "Discord_DeviceAuthorizationArgs_Scopes",
        constants$13.const$0
    );
    static final StructLayout const$2 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("opaque")
    ).withName("Discord_VoiceStateHandle");
    static final VarHandle const$3 = constants$62.const$2.varHandle(MemoryLayout.PathElement.groupElement("opaque"));
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "Discord_VoiceStateHandle_Drop",
        constants$0.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "Discord_VoiceStateHandle_Clone",
        constants$13.const$0
    );
}


