// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$114 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$114() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "Discord_Client_RegisterAuthorizeRequestCallback",
        constants$68.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "Discord_Client_RemoveAuthorizeRequestCallback",
        constants$0.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "Discord_Client_RevokeToken",
        constants$113.const$4
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "Discord_Client_SetAuthorizeDeviceScreenClosedCallback",
        constants$68.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "Discord_Client_SetGameWindowPid",
        constants$32.const$4
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "Discord_Client_SetTokenExpirationCallback",
        constants$68.const$2
    );
}


