// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$24 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$24() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(Discord_Client_OpenConnectedGamesSettingsInDiscordCallback.class, "apply", constants$13.const$0);
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(Discord_Client_OnStatusChanged.class, "apply", constants$12.const$1);
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(Discord_Client_CreateOrJoinLobbyCallback.class, "apply", constants$22.const$1);
    static final FunctionDescriptor const$3 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER,
        MemoryLayout.structLayout(
            RuntimeHelper.POINTER.withName("ptr"),
            JAVA_LONG.withName("size")
        ).withName("Discord_GuildChannelSpan"),
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(Discord_Client_GetGuildChannelsCallback.class, "apply", constants$24.const$3);
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        constants$24.const$3
    );
}


