// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$20 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$20() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(Discord_Client_UpdateProvisionalAccountDisplayNameCallback.class, "apply", constants$13.const$0);
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(Discord_Client_UpdateTokenCallback.class, "apply", constants$13.const$0);
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(Discord_Client_DeleteUserMessageCallback.class, "apply", constants$13.const$0);
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(Discord_Client_EditUserMessageCallback.class, "apply", constants$13.const$0);
    static final FunctionDescriptor const$4 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER,
        MemoryLayout.structLayout(
            RuntimeHelper.POINTER.withName("ptr"),
            JAVA_LONG.withName("size")
        ).withName("Discord_MessageHandleSpan"),
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(Discord_Client_GetLobbyMessagesCallback.class, "apply", constants$20.const$4);
}


