// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$29 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$29() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(Discord_Client_UpdateRichPresenceCallback.class, "apply", constants$13.const$0);
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(Discord_Client_UpdateRelationshipCallback.class, "apply", constants$13.const$0);
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(Discord_Client_SendFriendRequestCallback.class, "apply", constants$13.const$0);
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(Discord_Client_RelationshipCreatedCallback.class, "apply", constants$11.const$3);
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(Discord_Client_RelationshipDeletedCallback.class, "apply", constants$11.const$3);
    static final FunctionDescriptor const$5 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
}


