// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$51 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$51() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("opaque")
    ).withName("Discord_ClientResult");
    static final VarHandle const$1 = constants$51.const$0.varHandle(MemoryLayout.PathElement.groupElement("opaque"));
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "Discord_ClientResult_Drop",
        constants$0.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "Discord_ClientResult_Clone",
        constants$13.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "Discord_ClientResult_ToString",
        constants$13.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "Discord_ClientResult_SetType",
        constants$32.const$4
    );
}


