// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$21 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$21() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        constants$20.const$4
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER,
        MemoryLayout.structLayout(
            RuntimeHelper.POINTER.withName("ptr"),
            JAVA_LONG.withName("size")
        ).withName("Discord_UserMessageSummarySpan"),
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(Discord_Client_UserMessageSummariesCallback.class, "apply", constants$21.const$1);
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        constants$21.const$1
    );
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(Discord_Client_UserMessagesWithLimitCallback.class, "apply", constants$20.const$4);
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(Discord_Client_ProvisionalUserMergeRequiredCallback.class, "apply", constants$0.const$0);
}


