// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$13 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$13() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(Discord_Client_GetCurrentInputDeviceCallback.class, "apply", constants$13.const$0);
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        constants$13.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(Discord_Client_GetCurrentOutputDeviceCallback.class, "apply", constants$13.const$0);
    static final FunctionDescriptor const$4 = FunctionDescriptor.ofVoid(
        MemoryLayout.structLayout(
            RuntimeHelper.POINTER.withName("ptr"),
            JAVA_LONG.withName("size")
        ).withName("Discord_AudioDeviceSpan"),
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(Discord_Client_GetInputDevicesCallback.class, "apply", constants$13.const$4);
}


