// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$130 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$130() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "Discord_Client_GetCurrentUserV2",
        constants$36.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "Discord_Client_GetDiscordClientConnectedUser",
        constants$103.const$4
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "Discord_Client_GetUser",
        constants$67.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "Discord_Client_SetRelationshipGroupsUpdatedCallback",
        constants$68.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "Discord_Client_SetUserUpdatedCallback",
        constants$68.const$2
    );
    static final StructLayout const$5 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("opaque")
    ).withName("Discord_CallInfoHandle");
}


