// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$105 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$105() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "Discord_Client_GetInputVolume",
        constants$54.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "Discord_Client_GetOutputDevices",
        constants$68.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "Discord_Client_GetOutputVolume",
        constants$54.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "Discord_Client_GetSelfDeafAll",
        constants$35.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "Discord_Client_GetSelfMuteAll",
        constants$35.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "Discord_Client_SetAecDump",
        constants$34.const$5
    );
}


