// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$2 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$2() {}
    static final VarHandle const$0 = constants$1.const$3.varHandle(MemoryLayout.PathElement.groupElement("values"));
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        JAVA_LONG
    );
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(Discord_MallocFn.class, "apply", constants$2.const$1);
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        constants$2.const$1
    );
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(Discord_FreeFn.class, "apply", constants$0.const$0);
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        constants$0.const$0
    );
}


