// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$102 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$102() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "Discord_Client_GetDefaultCommunicationScopes",
        constants$0.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "Discord_Client_GetDefaultPresenceScopes",
        constants$0.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "Discord_Client_GetVersionHash",
        constants$0.const$0
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(JAVA_INT);
    static final MethodHandle const$4 = RuntimeHelper.downcallHandleVariadic(
        "Discord_Client_GetVersionMajor",
        constants$102.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandleVariadic(
        "Discord_Client_GetVersionMinor",
        constants$102.const$3
    );
}


