// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$4 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$4() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandleVariadic(
        "Discord_SetFreeThreaded",
        constants$0.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandleVariadic(
        "Discord_ResetCallbacks",
        constants$0.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandleVariadic(
        "Discord_RunCallbacks",
        constants$0.const$2
    );
    static final StructLayout const$3 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("ptr"),
        JAVA_LONG.withName("size")
    ).withName("Discord_String");
    static final VarHandle const$4 = constants$4.const$3.varHandle(MemoryLayout.PathElement.groupElement("ptr"));
    static final VarHandle const$5 = constants$4.const$3.varHandle(MemoryLayout.PathElement.groupElement("size"));
}


