// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$57 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$57() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "Discord_AuthorizationCodeVerifier_SetChallenge",
        constants$13.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "Discord_AuthorizationCodeVerifier_Challenge",
        constants$13.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "Discord_AuthorizationCodeVerifier_SetVerifier",
        constants$34.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "Discord_AuthorizationCodeVerifier_Verifier",
        constants$13.const$0
    );
    static final StructLayout const$4 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("opaque")
    ).withName("Discord_AuthorizationArgs");
    static final VarHandle const$5 = constants$57.const$4.varHandle(MemoryLayout.PathElement.groupElement("opaque"));
}


