// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$95 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$95() {}
    static final VarHandle const$0 = constants$94.const$5.varHandle(MemoryLayout.PathElement.groupElement("opaque"));
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "Discord_AudioDevice_Drop",
        constants$0.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "Discord_AudioDevice_Clone",
        constants$13.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "Discord_AudioDevice_Equals",
        constants$36.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "Discord_AudioDevice_SetId",
        constants$34.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "Discord_AudioDevice_Id",
        constants$13.const$0
    );
}


