// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$121 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$121() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "Discord_Client_CreateOrJoinLobby",
        constants$106.const$4
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER,
        MemoryLayout.structLayout(
            RuntimeHelper.POINTER.withName("ptr"),
            JAVA_LONG.withName("size")
        ).withName("Discord_String"),
        MemoryLayout.structLayout(
            JAVA_LONG.withName("size"),
            RuntimeHelper.POINTER.withName("keys"),
            RuntimeHelper.POINTER.withName("values")
        ).withName("Discord_Properties"),
        MemoryLayout.structLayout(
            JAVA_LONG.withName("size"),
            RuntimeHelper.POINTER.withName("keys"),
            RuntimeHelper.POINTER.withName("values")
        ).withName("Discord_Properties"),
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "Discord_Client_CreateOrJoinLobbyWithMetadata",
        constants$121.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "Discord_Client_GetGuildChannels",
        constants$103.const$4
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "Discord_Client_GetLobbyHandle",
        constants$67.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "Discord_Client_GetLobbyIds",
        constants$13.const$0
    );
}


