// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$128 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$128() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "Discord_Client_RejectDiscordFriendRequest",
        constants$103.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "Discord_Client_RejectGameFriendRequest",
        constants$103.const$4
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "Discord_Client_RemoveDiscordAndGameFriend",
        constants$103.const$4
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "Discord_Client_RemoveGameFriend",
        constants$103.const$4
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "Discord_Client_SearchFriendsByUsername",
        constants$25.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "Discord_Client_SendDiscordFriendRequest",
        constants$106.const$4
    );
}


