// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$67 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$67() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "Discord_Call_GetSelfMute",
        constants$35.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "Discord_Call_GetStatus",
        constants$33.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "Discord_Call_GetVADThreshold",
        constants$13.const$0
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(JAVA_BOOLEAN,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "Discord_Call_GetVoiceStateHandle",
        constants$67.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "Discord_Call_SetAudioMode",
        constants$32.const$4
    );
}


