// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$64 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$64() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "Discord_VADThresholdSettings_VadThreshold",
        constants$54.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "Discord_VADThresholdSettings_SetAutomatic",
        constants$34.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "Discord_VADThresholdSettings_Automatic",
        constants$35.const$0
    );
    static final StructLayout const$3 = MemoryLayout.structLayout(
        MemoryLayout.sequenceLayout(3, RuntimeHelper.POINTER).withName("opaque")
    ).withName("Discord_Call");
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "Discord_Call_Drop",
        constants$0.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "Discord_Call_Clone",
        constants$13.const$0
    );
}


