// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$14 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$14() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        constants$13.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(Discord_Client_GetOutputDevicesCallback.class, "apply", constants$13.const$4);
    static final FunctionDescriptor const$2 = FunctionDescriptor.ofVoid(
        MemoryLayout.structLayout(
            RuntimeHelper.POINTER.withName("ptr"),
            JAVA_LONG.withName("size")
        ).withName("Discord_AudioDeviceSpan"),
        MemoryLayout.structLayout(
            RuntimeHelper.POINTER.withName("ptr"),
            JAVA_LONG.withName("size")
        ).withName("Discord_AudioDeviceSpan"),
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(Discord_Client_DeviceChangeCallback.class, "apply", constants$14.const$2);
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        constants$14.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(Discord_Client_SetInputDeviceCallback.class, "apply", constants$13.const$0);
}


