// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$37 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$37() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "Discord_ActivityAssets_SetLargeUrl",
        constants$13.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "Discord_ActivityAssets_LargeUrl",
        constants$36.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "Discord_ActivityAssets_SetSmallImage",
        constants$13.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "Discord_ActivityAssets_SmallImage",
        constants$36.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "Discord_ActivityAssets_SetSmallText",
        constants$13.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "Discord_ActivityAssets_SmallText",
        constants$36.const$2
    );
}


