// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$58 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$58() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "Discord_AuthorizationArgs_Init",
        constants$0.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "Discord_AuthorizationArgs_Drop",
        constants$0.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "Discord_AuthorizationArgs_Clone",
        constants$13.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "Discord_AuthorizationArgs_SetClientId",
        constants$31.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "Discord_AuthorizationArgs_ClientId",
        constants$31.const$5
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "Discord_AuthorizationArgs_SetScopes",
        constants$34.const$0
    );
}


