// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$55 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$55() {}
    static final VarHandle const$0 = constants$54.const$5.varHandle(MemoryLayout.PathElement.groupElement("opaque"));
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "Discord_AuthorizationCodeChallenge_Init",
        constants$0.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "Discord_AuthorizationCodeChallenge_Drop",
        constants$0.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "Discord_AuthorizationCodeChallenge_Clone",
        constants$13.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "Discord_AuthorizationCodeChallenge_SetMethod",
        constants$32.const$4
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "Discord_AuthorizationCodeChallenge_Method",
        constants$33.const$0
    );
}


