// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$12 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$12() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(Discord_Call_OnSpeakingStatusChanged.class, "apply", constants$11.const$3);
    static final FunctionDescriptor const$1 = FunctionDescriptor.ofVoid(
        JAVA_INT,
        JAVA_INT,
        JAVA_INT,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(Discord_Call_OnStatusChanged.class, "apply", constants$12.const$1);
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        constants$12.const$1
    );
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(Discord_Client_EndCallCallback.class, "apply", constants$0.const$0);
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(Discord_Client_EndCallsCallback.class, "apply", constants$0.const$0);
}


