// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$59 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$59() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "Discord_AuthorizationArgs_Scopes",
        constants$13.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "Discord_AuthorizationArgs_SetState",
        constants$13.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "Discord_AuthorizationArgs_State",
        constants$36.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "Discord_AuthorizationArgs_SetNonce",
        constants$13.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "Discord_AuthorizationArgs_Nonce",
        constants$36.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "Discord_AuthorizationArgs_SetCodeChallenge",
        constants$13.const$0
    );
}


