// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$103 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$103() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandleVariadic(
        "Discord_Client_GetVersionPatch",
        constants$102.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "Discord_Client_SetHttpRequestTimeout",
        constants$32.const$4
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "Discord_Client_StatusToString",
        constants$65.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "Discord_Client_ThreadToString",
        constants$65.const$0
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER,
        JAVA_LONG,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "Discord_Client_EndCall",
        constants$103.const$4
    );
}


