// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$124 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$124() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "Discord_Client_ClearRichPresence",
        constants$0.const$0
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(JAVA_BOOLEAN,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        MemoryLayout.structLayout(
            RuntimeHelper.POINTER.withName("ptr"),
            JAVA_LONG.withName("size")
        ).withName("Discord_String")
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "Discord_Client_RegisterLaunchCommand",
        constants$124.const$1
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(JAVA_BOOLEAN,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        JAVA_INT
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "Discord_Client_RegisterLaunchSteamApplication",
        constants$124.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "Discord_Client_SendActivityInvite",
        constants$113.const$4
    );
}


