// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$60 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$60() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "Discord_AuthorizationArgs_CodeChallenge",
        constants$36.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "Discord_AuthorizationArgs_SetIntegrationType",
        constants$13.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "Discord_AuthorizationArgs_IntegrationType",
        constants$36.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "Discord_AuthorizationArgs_SetCustomSchemeParam",
        constants$13.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "Discord_AuthorizationArgs_CustomSchemeParam",
        constants$36.const$2
    );
    static final StructLayout const$5 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("opaque")
    ).withName("Discord_DeviceAuthorizationArgs");
}


