// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$53 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$53() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "Discord_ClientResult_Status",
        constants$33.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "Discord_ClientResult_SetResponseBody",
        constants$34.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "Discord_ClientResult_ResponseBody",
        constants$13.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "Discord_ClientResult_SetSuccessful",
        constants$34.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "Discord_ClientResult_Successful",
        constants$35.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "Discord_ClientResult_SetRetryable",
        constants$34.const$5
    );
}


