// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$92 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$92() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "Discord_MessageHandle_AdditionalContent",
        constants$36.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "Discord_MessageHandle_ApplicationId",
        constants$36.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "Discord_MessageHandle_Author",
        constants$36.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "Discord_MessageHandle_AuthorId",
        constants$31.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "Discord_MessageHandle_Channel",
        constants$36.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "Discord_MessageHandle_ChannelId",
        constants$31.const$5
    );
}


