// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$69 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$69() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "Discord_Call_SetPTTActive",
        constants$34.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "Discord_Call_SetPTTReleaseDelay",
        constants$32.const$4
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "Discord_Call_SetSelfDeaf",
        constants$34.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "Discord_Call_SetSelfMute",
        constants$34.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "Discord_Call_SetSpeakingStatusChangedCallback",
        constants$68.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "Discord_Call_SetStatusChangedCallback",
        constants$68.const$2
    );
}


