// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$73 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$73() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "Discord_GuildMinimal_Name",
        constants$13.const$0
    );
    static final StructLayout const$1 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("opaque")
    ).withName("Discord_GuildChannel");
    static final VarHandle const$2 = constants$73.const$1.varHandle(MemoryLayout.PathElement.groupElement("opaque"));
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "Discord_GuildChannel_Drop",
        constants$0.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "Discord_GuildChannel_Clone",
        constants$13.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "Discord_GuildChannel_SetId",
        constants$31.const$3
    );
}


