// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$90 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$90() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "Discord_AdditionalContent_SetType",
        constants$32.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "Discord_AdditionalContent_Type",
        constants$33.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "Discord_AdditionalContent_SetTitle",
        constants$13.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "Discord_AdditionalContent_Title",
        constants$36.const$2
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER,
        JAVA_BYTE
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "Discord_AdditionalContent_SetCount",
        constants$90.const$4
    );
}


