// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$63 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$63() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "Discord_VoiceStateHandle_SelfDeaf",
        constants$35.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "Discord_VoiceStateHandle_SelfMute",
        constants$35.const$0
    );
    static final StructLayout const$2 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("opaque")
    ).withName("Discord_VADThresholdSettings");
    static final VarHandle const$3 = constants$63.const$2.varHandle(MemoryLayout.PathElement.groupElement("opaque"));
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "Discord_VADThresholdSettings_Drop",
        constants$0.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "Discord_VADThresholdSettings_SetVadThreshold",
        constants$54.const$1
    );
}


