// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$26 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$26() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(Discord_Client_LeaveLobbyCallback.class, "apply", constants$13.const$0);
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(Discord_Client_LinkOrUnlinkChannelCallback.class, "apply", constants$13.const$0);
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(Discord_Client_LobbyCreatedCallback.class, "apply", constants$11.const$0);
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(Discord_Client_LobbyDeletedCallback.class, "apply", constants$11.const$0);
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(Discord_Client_LobbyMemberAddedCallback.class, "apply", constants$22.const$5);
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(Discord_Client_LobbyMemberRemovedCallback.class, "apply", constants$22.const$5);
}


