// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$96 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$96() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "Discord_AudioDevice_SetName",
        constants$34.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "Discord_AudioDevice_Name",
        constants$13.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "Discord_AudioDevice_SetIsDefault",
        constants$34.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "Discord_AudioDevice_IsDefault",
        constants$35.const$0
    );
    static final StructLayout const$4 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("opaque")
    ).withName("Discord_UserMessageSummary");
    static final VarHandle const$5 = constants$96.const$4.varHandle(MemoryLayout.PathElement.groupElement("opaque"));
}


