// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$74 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$74() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "Discord_GuildChannel_Id",
        constants$31.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "Discord_GuildChannel_SetName",
        constants$34.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "Discord_GuildChannel_Name",
        constants$13.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "Discord_GuildChannel_SetType",
        constants$32.const$4
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "Discord_GuildChannel_Type",
        constants$33.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "Discord_GuildChannel_SetPosition",
        constants$32.const$4
    );
}


