// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$132 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$132() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "Discord_CallInfoHandle_GuildId",
        constants$31.const$5
    );
    static final MemorySegment const$1 = MemorySegment.ofAddress(0L);
}


