// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$32 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$32() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "Discord_ActivityInvite_SetChannelId",
        constants$31.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "Discord_ActivityInvite_ChannelId",
        constants$31.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "Discord_ActivityInvite_SetMessageId",
        constants$31.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "Discord_ActivityInvite_MessageId",
        constants$31.const$5
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER,
        JAVA_INT
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "Discord_ActivityInvite_SetType",
        constants$32.const$4
    );
}


