// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$86 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$86() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "Discord_LobbyMemberHandle_Clone",
        constants$13.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "Discord_LobbyMemberHandle_CanLinkLobby",
        constants$35.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "Discord_LobbyMemberHandle_Connected",
        constants$35.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "Discord_LobbyMemberHandle_Id",
        constants$31.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "Discord_LobbyMemberHandle_Metadata",
        constants$13.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "Discord_LobbyMemberHandle_User",
        constants$36.const$2
    );
}


