// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$97 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$97() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "Discord_UserMessageSummary_Drop",
        constants$0.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "Discord_UserMessageSummary_Clone",
        constants$13.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "Discord_UserMessageSummary_LastMessageId",
        constants$31.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "Discord_UserMessageSummary_UserId",
        constants$31.const$5
    );
    static final StructLayout const$4 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("opaque")
    ).withName("Discord_ClientCreateOptions");
    static final VarHandle const$5 = constants$97.const$4.varHandle(MemoryLayout.PathElement.groupElement("opaque"));
}


