// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$47 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$47() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "Discord_Activity_SetStatusDisplayType",
        constants$13.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "Discord_Activity_StatusDisplayType",
        constants$36.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "Discord_Activity_SetState",
        constants$13.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "Discord_Activity_State",
        constants$36.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "Discord_Activity_SetStateUrl",
        constants$13.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "Discord_Activity_StateUrl",
        constants$36.const$2
    );
}


