// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$54 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$54() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "Discord_ClientResult_Retryable",
        constants$35.const$0
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER,
        JAVA_FLOAT
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "Discord_ClientResult_SetRetryAfter",
        constants$54.const$1
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(JAVA_FLOAT,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "Discord_ClientResult_RetryAfter",
        constants$54.const$3
    );
    static final StructLayout const$5 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("opaque")
    ).withName("Discord_AuthorizationCodeChallenge");
}


