// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$6 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$6() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("ptr"),
        JAVA_LONG.withName("size")
    ).withName("Discord_UserApplicationProfileHandleSpan");
    static final VarHandle const$1 = constants$6.const$0.varHandle(MemoryLayout.PathElement.groupElement("ptr"));
    static final VarHandle const$2 = constants$6.const$0.varHandle(MemoryLayout.PathElement.groupElement("size"));
    static final StructLayout const$3 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("ptr"),
        JAVA_LONG.withName("size")
    ).withName("Discord_LobbyMemberHandleSpan");
    static final VarHandle const$4 = constants$6.const$3.varHandle(MemoryLayout.PathElement.groupElement("ptr"));
    static final VarHandle const$5 = constants$6.const$3.varHandle(MemoryLayout.PathElement.groupElement("size"));
}


