// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$72 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$72() {}
    static final VarHandle const$0 = constants$71.const$5.varHandle(MemoryLayout.PathElement.groupElement("opaque"));
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "Discord_GuildMinimal_Drop",
        constants$0.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "Discord_GuildMinimal_Clone",
        constants$13.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "Discord_GuildMinimal_SetId",
        constants$31.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "Discord_GuildMinimal_Id",
        constants$31.const$5
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "Discord_GuildMinimal_SetName",
        constants$34.const$0
    );
}


