// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$70 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$70() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER,
        JAVA_BOOLEAN,
        JAVA_FLOAT
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "Discord_Call_SetVADThreshold",
        constants$70.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "Discord_Call_StatusToString",
        constants$65.const$0
    );
    static final StructLayout const$3 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("opaque")
    ).withName("Discord_ChannelHandle");
    static final VarHandle const$4 = constants$70.const$3.varHandle(MemoryLayout.PathElement.groupElement("opaque"));
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "Discord_ChannelHandle_Drop",
        constants$0.const$0
    );
}


