// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$19 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$19() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        constants$18.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(Discord_Client_AuthorizeRequestCallback.class, "apply", constants$0.const$0);
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(Discord_Client_RevokeTokenCallback.class, "apply", constants$13.const$0);
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(Discord_Client_AuthorizeDeviceScreenClosedCallback.class, "apply", constants$0.const$0);
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(Discord_Client_TokenExpirationCallback.class, "apply", constants$0.const$0);
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(Discord_Client_UnmergeIntoProvisionalAccountCallback.class, "apply", constants$13.const$0);
}


