// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$118 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$118() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "Discord_Client_SendUserMessage",
        constants$113.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "Discord_Client_SendUserMessageWithMetadata",
        constants$117.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "Discord_Client_SetMessageCreatedCallback",
        constants$68.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "Discord_Client_SetMessageDeletedCallback",
        constants$68.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "Discord_Client_SetMessageUpdatedCallback",
        constants$68.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "Discord_Client_SetShowingChat",
        constants$34.const$5
    );
}


