// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$15 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$15() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.ofVoid(
        JAVA_BOOLEAN,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(Discord_Client_NoAudioInputCallback.class, "apply", constants$15.const$0);
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        constants$15.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(Discord_Client_SetOutputDeviceCallback.class, "apply", constants$13.const$0);
    static final FunctionDescriptor const$4 = FunctionDescriptor.ofVoid(
        JAVA_LONG,
        JAVA_LONG,
        JAVA_BOOLEAN,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(Discord_Client_VoiceParticipantChangedCallback.class, "apply", constants$15.const$4);
}


