// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$23 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$23() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(Discord_Client_MessageDeletedCallback.class, "apply", constants$22.const$5);
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        constants$22.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(Discord_Client_MessageUpdatedCallback.class, "apply", constants$11.const$0);
    static final FunctionDescriptor const$3 = FunctionDescriptor.ofVoid(
        MemoryLayout.structLayout(
            RuntimeHelper.POINTER.withName("ptr"),
            JAVA_LONG.withName("size")
        ).withName("Discord_String"),
        JAVA_INT,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(Discord_Client_LogCallback.class, "apply", constants$23.const$3);
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        constants$23.const$3
    );
}


