// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$78 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$78() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("opaque")
    ).withName("Discord_LinkedChannel");
    static final VarHandle const$1 = constants$78.const$0.varHandle(MemoryLayout.PathElement.groupElement("opaque"));
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "Discord_LinkedChannel_Drop",
        constants$0.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "Discord_LinkedChannel_Clone",
        constants$13.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "Discord_LinkedChannel_SetId",
        constants$31.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "Discord_LinkedChannel_Id",
        constants$31.const$5
    );
}


