// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$40 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$40() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "Discord_ActivityTimestamps_End",
        constants$31.const$5
    );
    static final StructLayout const$1 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("opaque")
    ).withName("Discord_ActivityParty");
    static final VarHandle const$2 = constants$40.const$1.varHandle(MemoryLayout.PathElement.groupElement("opaque"));
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "Discord_ActivityParty_Init",
        constants$0.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "Discord_ActivityParty_Drop",
        constants$0.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "Discord_ActivityParty_Clone",
        constants$13.const$0
    );
}


