// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$126 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$126() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER,
        JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "Discord_Client_SetOnlineStatus",
        constants$126.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "Discord_Client_UpdateRichPresence",
        constants$110.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "Discord_Client_AcceptDiscordFriendRequest",
        constants$103.const$4
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "Discord_Client_AcceptGameFriendRequest",
        constants$103.const$4
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "Discord_Client_BlockUser",
        constants$103.const$4
    );
}


