// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$27 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$27() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(Discord_Client_LobbyMemberUpdatedCallback.class, "apply", constants$22.const$5);
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(Discord_Client_LobbyUpdatedCallback.class, "apply", constants$11.const$0);
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(Discord_Client_AcceptActivityInviteCallback.class, "apply", constants$25.const$3);
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(Discord_Client_SendActivityInviteCallback.class, "apply", constants$13.const$0);
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(Discord_Client_ActivityInviteCallback.class, "apply", constants$13.const$0);
    static final FunctionDescriptor const$5 = FunctionDescriptor.ofVoid(
        MemoryLayout.structLayout(
            RuntimeHelper.POINTER.withName("ptr"),
            JAVA_LONG.withName("size")
        ).withName("Discord_String"),
        RuntimeHelper.POINTER
    );
}


