// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$28 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$28() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(Discord_Client_ActivityJoinCallback.class, "apply", constants$27.const$5);
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        constants$27.const$5
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.ofVoid(
        JAVA_LONG,
        MemoryLayout.structLayout(
            RuntimeHelper.POINTER.withName("ptr"),
            JAVA_LONG.withName("size")
        ).withName("Discord_String"),
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(Discord_Client_ActivityJoinWithApplicationCallback.class, "apply", constants$28.const$2);
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        constants$28.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(Discord_Client_UpdateStatusCallback.class, "apply", constants$13.const$0);
}


