// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$106 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$106() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "Discord_Client_SetAutomaticGainControl",
        constants$34.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "Discord_Client_SetDeviceChangeCallback",
        constants$68.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "Discord_Client_SetEchoCancellation",
        constants$34.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "Discord_Client_SetEngineManagedAudioSession",
        constants$34.const$5
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER,
        MemoryLayout.structLayout(
            RuntimeHelper.POINTER.withName("ptr"),
            JAVA_LONG.withName("size")
        ).withName("Discord_String"),
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "Discord_Client_SetInputDevice",
        constants$106.const$4
    );
}


