// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$22 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$22() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(Discord_Client_OpenMessageInDiscordCallback.class, "apply", constants$13.const$0);
    static final FunctionDescriptor const$1 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER,
        JAVA_LONG,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(Discord_Client_SendUserMessageCallback.class, "apply", constants$22.const$1);
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        constants$22.const$1
    );
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(Discord_Client_MessageCreatedCallback.class, "apply", constants$11.const$0);
    static final FunctionDescriptor const$5 = FunctionDescriptor.ofVoid(
        JAVA_LONG,
        JAVA_LONG,
        RuntimeHelper.POINTER
    );
}


