// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$81 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$81() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "Discord_RelationshipHandle_User",
        constants$36.const$2
    );
    static final StructLayout const$1 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("opaque")
    ).withName("Discord_UserApplicationProfileHandle");
    static final VarHandle const$2 = constants$81.const$1.varHandle(MemoryLayout.PathElement.groupElement("opaque"));
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "Discord_UserApplicationProfileHandle_Drop",
        constants$0.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "Discord_UserApplicationProfileHandle_Clone",
        constants$13.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "Discord_UserApplicationProfileHandle_AvatarHash",
        constants$13.const$0
    );
}


