// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$85 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$85() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "Discord_UserHandle_Status",
        constants$33.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "Discord_UserHandle_UserApplicationProfiles",
        constants$13.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "Discord_UserHandle_Username",
        constants$13.const$0
    );
    static final StructLayout const$3 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("opaque")
    ).withName("Discord_LobbyMemberHandle");
    static final VarHandle const$4 = constants$85.const$3.varHandle(MemoryLayout.PathElement.groupElement("opaque"));
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "Discord_LobbyMemberHandle_Drop",
        constants$0.const$0
    );
}


