// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$122 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$122() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "Discord_Client_GetUserGuilds",
        constants$68.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "Discord_Client_JoinLinkedLobbyGuild",
        constants$117.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "Discord_Client_LeaveLobby",
        constants$103.const$4
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "Discord_Client_LinkChannelToLobby",
        constants$115.const$4
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "Discord_Client_SetLobbyCreatedCallback",
        constants$68.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "Discord_Client_SetLobbyDeletedCallback",
        constants$68.const$2
    );
}


