// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$33 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$33() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "Discord_ActivityInvite_Type",
        constants$33.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "Discord_ActivityInvite_SetApplicationId",
        constants$31.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "Discord_ActivityInvite_ApplicationId",
        constants$31.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "Discord_ActivityInvite_SetParentApplicationId",
        constants$31.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "Discord_ActivityInvite_ParentApplicationId",
        constants$31.const$5
    );
}


