// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$99 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$99() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "Discord_ClientCreateOptions_ApiBase",
        constants$13.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "Discord_ClientCreateOptions_SetExperimentalAudioSystem",
        constants$32.const$4
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "Discord_ClientCreateOptions_ExperimentalAudioSystem",
        constants$33.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "Discord_ClientCreateOptions_SetExperimentalAndroidPreventCommsForBluetooth",
        constants$34.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "Discord_ClientCreateOptions_ExperimentalAndroidPreventCommsForBluetooth",
        constants$35.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "Discord_ClientCreateOptions_SetCpuAffinityMask",
        constants$13.const$0
    );
}


