// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$117 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$117() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "Discord_Client_GetUserMessageSummaries",
        constants$68.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "Discord_Client_GetUserMessagesWithLimit",
        constants$116.const$3
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER,
        JAVA_LONG,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "Discord_Client_OpenMessageInDiscord",
        constants$117.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "Discord_Client_SendLobbyMessage",
        constants$113.const$4
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER,
        JAVA_LONG,
        MemoryLayout.structLayout(
            RuntimeHelper.POINTER.withName("ptr"),
            JAVA_LONG.withName("size")
        ).withName("Discord_String"),
        MemoryLayout.structLayout(
            JAVA_LONG.withName("size"),
            RuntimeHelper.POINTER.withName("keys"),
            RuntimeHelper.POINTER.withName("values")
        ).withName("Discord_Properties"),
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "Discord_Client_SendLobbyMessageWithMetadata",
        constants$117.const$5
    );
}


