// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$41 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$41() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "Discord_ActivityParty_SetId",
        constants$34.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "Discord_ActivityParty_Id",
        constants$13.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "Discord_ActivityParty_SetCurrentSize",
        constants$32.const$4
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "Discord_ActivityParty_CurrentSize",
        constants$33.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "Discord_ActivityParty_SetMaxSize",
        constants$32.const$4
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "Discord_ActivityParty_MaxSize",
        constants$33.const$0
    );
}


