// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$25 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$25() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER,
        MemoryLayout.structLayout(
            RuntimeHelper.POINTER.withName("ptr"),
            JAVA_LONG.withName("size")
        ).withName("Discord_GuildMinimalSpan"),
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(Discord_Client_GetUserGuildsCallback.class, "apply", constants$25.const$0);
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        constants$25.const$0
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER,
        MemoryLayout.structLayout(
            RuntimeHelper.POINTER.withName("ptr"),
            JAVA_LONG.withName("size")
        ).withName("Discord_String"),
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(Discord_Client_JoinLinkedLobbyGuildCallback.class, "apply", constants$25.const$3);
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        constants$25.const$3
    );
}


