// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$49 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$49() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "Discord_Activity_SetParentApplicationId",
        constants$13.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "Discord_Activity_ParentApplicationId",
        constants$36.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "Discord_Activity_SetAssets",
        constants$13.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "Discord_Activity_Assets",
        constants$36.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "Discord_Activity_SetTimestamps",
        constants$13.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "Discord_Activity_Timestamps",
        constants$36.const$2
    );
}


