// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$125 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$125() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "Discord_Client_SendActivityJoinRequest",
        constants$103.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "Discord_Client_SendActivityJoinRequestReply",
        constants$110.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "Discord_Client_SetActivityInviteCreatedCallback",
        constants$68.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "Discord_Client_SetActivityInviteUpdatedCallback",
        constants$68.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "Discord_Client_SetActivityJoinCallback",
        constants$68.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "Discord_Client_SetActivityJoinWithApplicationCallback",
        constants$68.const$2
    );
}


