// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$3 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$3() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("fnMalloc"),
        RuntimeHelper.POINTER.withName("fnFree")
    ).withName("Discord_Allocator");
    static final VarHandle const$1 = constants$3.const$0.varHandle(MemoryLayout.PathElement.groupElement("fnMalloc"));
    static final VarHandle const$2 = constants$3.const$0.varHandle(MemoryLayout.PathElement.groupElement("fnFree"));
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "Discord_Alloc",
        constants$2.const$1
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "Discord_Free",
        constants$0.const$0
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.ofVoid(
        MemoryLayout.structLayout(
            JAVA_LONG.withName("size"),
            RuntimeHelper.POINTER.withName("keys"),
            RuntimeHelper.POINTER.withName("values")
        ).withName("Discord_Properties")
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "Discord_FreeProperties",
        constants$3.const$5
    );
}


