// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$127 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$127() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "Discord_Client_CancelDiscordFriendRequest",
        constants$103.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "Discord_Client_CancelGameFriendRequest",
        constants$103.const$4
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "Discord_Client_GetRelationshipHandle",
        constants$22.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "Discord_Client_GetRelationships",
        constants$13.const$0
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER,
        JAVA_INT,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "Discord_Client_GetRelationshipsByGroup",
        constants$127.const$4
    );
}


