// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$11 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$11() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.ofVoid(
        JAVA_LONG,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(Discord_Call_OnVoiceStateChanged.class, "apply", constants$11.const$0);
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        constants$11.const$0
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.ofVoid(
        JAVA_LONG,
        JAVA_BOOLEAN,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(Discord_Call_OnParticipantChanged.class, "apply", constants$11.const$3);
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        constants$11.const$3
    );
}


