/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.frostclient.discord;

public final class Discord_IntegrationType {
  public final static Discord_IntegrationType Discord_IntegrationType_GuildInstall = new Discord_IntegrationType("Discord_IntegrationType_GuildInstall", discordJNI.Discord_IntegrationType_GuildInstall_get());
  public final static Discord_IntegrationType Discord_IntegrationType_UserInstall = new Discord_IntegrationType("Discord_IntegrationType_UserInstall", discordJNI.Discord_IntegrationType_UserInstall_get());
  public final static Discord_IntegrationType Discord_IntegrationType_forceint = new Discord_IntegrationType("Discord_IntegrationType_forceint", discordJNI.Discord_IntegrationType_forceint_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static Discord_IntegrationType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + Discord_IntegrationType.class + " with value " + swigValue);
  }

  private Discord_IntegrationType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private Discord_IntegrationType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private Discord_IntegrationType(String swigName, Discord_IntegrationType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static Discord_IntegrationType[] swigValues = { Discord_IntegrationType_GuildInstall, Discord_IntegrationType_UserInstall, Discord_IntegrationType_forceint };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

