/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.frostclient.discord;

public class Discord_Properties {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Discord_Properties(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Discord_Properties obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(Discord_Properties obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        discordJNI.delete_Discord_Properties(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSize(long value) {
    discordJNI.Discord_Properties_size_set(swigCPtr, this, value);
  }

  public long getSize() {
    return discordJNI.Discord_Properties_size_get(swigCPtr, this);
  }

  public void setKeys(Discord_String value) {
    discordJNI.Discord_Properties_keys_set(swigCPtr, this, Discord_String.getCPtr(value), value);
  }

  public Discord_String getKeys() {
    long cPtr = discordJNI.Discord_Properties_keys_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Discord_String(cPtr, false);
  }

  public void setValues(Discord_String value) {
    discordJNI.Discord_Properties_values_set(swigCPtr, this, Discord_String.getCPtr(value), value);
  }

  public Discord_String getValues() {
    long cPtr = discordJNI.Discord_Properties_values_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Discord_String(cPtr, false);
  }

  public Discord_Properties() {
    this(discordJNI.new_Discord_Properties(), true);
  }

}
