// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * void (*Discord_Client_GetDiscordClientConnectedUserCallback)(struct Discord_ClientResult* result,struct Discord_UserHandle* user,void* userData);
 * }
 */
public interface Discord_Client_GetDiscordClientConnectedUserCallback {

    void apply(java.lang.foreign.MemorySegment result, java.lang.foreign.MemorySegment user, java.lang.foreign.MemorySegment userData);
    static MemorySegment allocate(Discord_Client_GetDiscordClientConnectedUserCallback fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$30.const$0, fi, constants$29.const$5, scope);
    }
    static Discord_Client_GetDiscordClientConnectedUserCallback ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment _result, java.lang.foreign.MemorySegment _user, java.lang.foreign.MemorySegment _userData) -> {
            try {
                constants$30.const$1.invokeExact(symbol, _result, _user, _userData);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


