/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.frostclient.discord;

public final class Discord_ChannelType {
  public final static Discord_ChannelType Discord_ChannelType_GuildText = new Discord_ChannelType("Discord_ChannelType_GuildText", discordJNI.Discord_ChannelType_GuildText_get());
  public final static Discord_ChannelType Discord_ChannelType_Dm = new Discord_ChannelType("Discord_ChannelType_Dm", discordJNI.Discord_ChannelType_Dm_get());
  public final static Discord_ChannelType Discord_ChannelType_GuildVoice = new Discord_ChannelType("Discord_ChannelType_GuildVoice", discordJNI.Discord_ChannelType_GuildVoice_get());
  public final static Discord_ChannelType Discord_ChannelType_GroupDm = new Discord_ChannelType("Discord_ChannelType_GroupDm", discordJNI.Discord_ChannelType_GroupDm_get());
  public final static Discord_ChannelType Discord_ChannelType_GuildCategory = new Discord_ChannelType("Discord_ChannelType_GuildCategory", discordJNI.Discord_ChannelType_GuildCategory_get());
  public final static Discord_ChannelType Discord_ChannelType_GuildNews = new Discord_ChannelType("Discord_ChannelType_GuildNews", discordJNI.Discord_ChannelType_GuildNews_get());
  public final static Discord_ChannelType Discord_ChannelType_GuildStore = new Discord_ChannelType("Discord_ChannelType_GuildStore", discordJNI.Discord_ChannelType_GuildStore_get());
  public final static Discord_ChannelType Discord_ChannelType_GuildNewsThread = new Discord_ChannelType("Discord_ChannelType_GuildNewsThread", discordJNI.Discord_ChannelType_GuildNewsThread_get());
  public final static Discord_ChannelType Discord_ChannelType_GuildPublicThread = new Discord_ChannelType("Discord_ChannelType_GuildPublicThread", discordJNI.Discord_ChannelType_GuildPublicThread_get());
  public final static Discord_ChannelType Discord_ChannelType_GuildPrivateThread = new Discord_ChannelType("Discord_ChannelType_GuildPrivateThread", discordJNI.Discord_ChannelType_GuildPrivateThread_get());
  public final static Discord_ChannelType Discord_ChannelType_GuildStageVoice = new Discord_ChannelType("Discord_ChannelType_GuildStageVoice", discordJNI.Discord_ChannelType_GuildStageVoice_get());
  public final static Discord_ChannelType Discord_ChannelType_GuildDirectory = new Discord_ChannelType("Discord_ChannelType_GuildDirectory", discordJNI.Discord_ChannelType_GuildDirectory_get());
  public final static Discord_ChannelType Discord_ChannelType_GuildForum = new Discord_ChannelType("Discord_ChannelType_GuildForum", discordJNI.Discord_ChannelType_GuildForum_get());
  public final static Discord_ChannelType Discord_ChannelType_GuildMedia = new Discord_ChannelType("Discord_ChannelType_GuildMedia", discordJNI.Discord_ChannelType_GuildMedia_get());
  public final static Discord_ChannelType Discord_ChannelType_Lobby = new Discord_ChannelType("Discord_ChannelType_Lobby", discordJNI.Discord_ChannelType_Lobby_get());
  public final static Discord_ChannelType Discord_ChannelType_EphemeralDm = new Discord_ChannelType("Discord_ChannelType_EphemeralDm", discordJNI.Discord_ChannelType_EphemeralDm_get());
  public final static Discord_ChannelType Discord_ChannelType_forceint = new Discord_ChannelType("Discord_ChannelType_forceint", discordJNI.Discord_ChannelType_forceint_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static Discord_ChannelType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + Discord_ChannelType.class + " with value " + swigValue);
  }

  private Discord_ChannelType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private Discord_ChannelType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private Discord_ChannelType(String swigName, Discord_ChannelType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static Discord_ChannelType[] swigValues = { Discord_ChannelType_GuildText, Discord_ChannelType_Dm, Discord_ChannelType_GuildVoice, Discord_ChannelType_GroupDm, Discord_ChannelType_GuildCategory, Discord_ChannelType_GuildNews, Discord_ChannelType_GuildStore, Discord_ChannelType_GuildNewsThread, Discord_ChannelType_GuildPublicThread, Discord_ChannelType_GuildPrivateThread, Discord_ChannelType_GuildStageVoice, Discord_ChannelType_GuildDirectory, Discord_ChannelType_GuildForum, Discord_ChannelType_GuildMedia, Discord_ChannelType_Lobby, Discord_ChannelType_EphemeralDm, Discord_ChannelType_forceint };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

