// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * void (*Discord_Client_LobbyCreatedCallback)(unsigned long long lobbyId,void* userData);
 * }
 */
public interface Discord_Client_LobbyCreatedCallback {

    void apply(long userId, java.lang.foreign.MemorySegment userData);
    static MemorySegment allocate(Discord_Client_LobbyCreatedCallback fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$26.const$2, fi, constants$11.const$0, scope);
    }
    static Discord_Client_LobbyCreatedCallback ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (long _userId, java.lang.foreign.MemorySegment _userData) -> {
            try {
                constants$11.const$2.invokeExact(symbol, _userId, _userData);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


