/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.frostclient.discord;

public final class Discord_LoggingSeverity {
  public final static Discord_LoggingSeverity Discord_LoggingSeverity_Verbose = new Discord_LoggingSeverity("Discord_LoggingSeverity_Verbose", discordJNI.Discord_LoggingSeverity_Verbose_get());
  public final static Discord_LoggingSeverity Discord_LoggingSeverity_Info = new Discord_LoggingSeverity("Discord_LoggingSeverity_Info", discordJNI.Discord_LoggingSeverity_Info_get());
  public final static Discord_LoggingSeverity Discord_LoggingSeverity_Warning = new Discord_LoggingSeverity("Discord_LoggingSeverity_Warning", discordJNI.Discord_LoggingSeverity_Warning_get());
  public final static Discord_LoggingSeverity Discord_LoggingSeverity_Error = new Discord_LoggingSeverity("Discord_LoggingSeverity_Error", discordJNI.Discord_LoggingSeverity_Error_get());
  public final static Discord_LoggingSeverity Discord_LoggingSeverity_None = new Discord_LoggingSeverity("Discord_LoggingSeverity_None", discordJNI.Discord_LoggingSeverity_None_get());
  public final static Discord_LoggingSeverity Discord_LoggingSeverity_forceint = new Discord_LoggingSeverity("Discord_LoggingSeverity_forceint", discordJNI.Discord_LoggingSeverity_forceint_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static Discord_LoggingSeverity swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + Discord_LoggingSeverity.class + " with value " + swigValue);
  }

  private Discord_LoggingSeverity(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private Discord_LoggingSeverity(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private Discord_LoggingSeverity(String swigName, Discord_LoggingSeverity swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static Discord_LoggingSeverity[] swigValues = { Discord_LoggingSeverity_Verbose, Discord_LoggingSeverity_Info, Discord_LoggingSeverity_Warning, Discord_LoggingSeverity_Error, Discord_LoggingSeverity_None, Discord_LoggingSeverity_forceint };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

