// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct Discord_GuildMinimalSpan {
 *     Discord_GuildMinimal* ptr;
 *     size_t size;
 * };
 * }
 */
public class Discord_GuildMinimalSpan {

    public static MemoryLayout $LAYOUT() {
        return constants$9.const$3;
    }
    public static VarHandle ptr$VH() {
        return constants$9.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * Discord_GuildMinimal* ptr;
     * }
     */
    public static MemorySegment ptr$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$9.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * Discord_GuildMinimal* ptr;
     * }
     */
    public static void ptr$set(MemorySegment seg, MemorySegment x) {
        constants$9.const$4.set(seg, x);
    }
    public static MemorySegment ptr$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$9.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void ptr$set(MemorySegment seg, long index, MemorySegment x) {
        constants$9.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle size$VH() {
        return constants$9.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * size_t size;
     * }
     */
    public static long size$get(MemorySegment seg) {
        return (long)constants$9.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * size_t size;
     * }
     */
    public static void size$set(MemorySegment seg, long x) {
        constants$9.const$5.set(seg, x);
    }
    public static long size$get(MemorySegment seg, long index) {
        return (long)constants$9.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void size$set(MemorySegment seg, long index, long x) {
        constants$9.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


