// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * void (*Discord_Client_ActivityJoinWithApplicationCallback)(unsigned long long applicationId,struct Discord_String joinSecret,void* userData);
 * }
 */
public interface Discord_Client_ActivityJoinWithApplicationCallback {

    void apply(long applicationId, java.lang.foreign.MemorySegment joinSecret, java.lang.foreign.MemorySegment userData);
    static MemorySegment allocate(Discord_Client_ActivityJoinWithApplicationCallback fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$28.const$3, fi, constants$28.const$2, scope);
    }
    static Discord_Client_ActivityJoinWithApplicationCallback ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (long _applicationId, java.lang.foreign.MemorySegment _joinSecret, java.lang.foreign.MemorySegment _userData) -> {
            try {
                constants$28.const$4.invokeExact(symbol, _applicationId, _joinSecret, _userData);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


