// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * void (*Discord_Client_NoAudioInputCallback)(_Bool inputDetected,void* userData);
 * }
 */
public interface Discord_Client_NoAudioInputCallback {

    void apply(boolean inputDetected, java.lang.foreign.MemorySegment userData);
    static MemorySegment allocate(Discord_Client_NoAudioInputCallback fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$15.const$1, fi, constants$15.const$0, scope);
    }
    static Discord_Client_NoAudioInputCallback ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (boolean _inputDetected, java.lang.foreign.MemorySegment _userData) -> {
            try {
                constants$15.const$2.invokeExact(symbol, _inputDetected, _userData);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


