// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * void (*Discord_Client_GetCurrentInputDeviceCallback)(struct Discord_AudioDevice* device,void* userData);
 * }
 */
public interface Discord_Client_GetCurrentInputDeviceCallback {

    void apply(java.lang.foreign.MemorySegment result, java.lang.foreign.MemorySegment userData);
    static MemorySegment allocate(Discord_Client_GetCurrentInputDeviceCallback fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$13.const$1, fi, constants$13.const$0, scope);
    }
    static Discord_Client_GetCurrentInputDeviceCallback ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment _result, java.lang.foreign.MemorySegment _userData) -> {
            try {
                constants$13.const$2.invokeExact(symbol, _result, _userData);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


