/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.frostclient.discord;

public final class Discord_AuthorizationTokenType {
  public final static Discord_AuthorizationTokenType Discord_AuthorizationTokenType_User = new Discord_AuthorizationTokenType("Discord_AuthorizationTokenType_User", discordJNI.Discord_AuthorizationTokenType_User_get());
  public final static Discord_AuthorizationTokenType Discord_AuthorizationTokenType_Bearer = new Discord_AuthorizationTokenType("Discord_AuthorizationTokenType_Bearer", discordJNI.Discord_AuthorizationTokenType_Bearer_get());
  public final static Discord_AuthorizationTokenType Discord_AuthorizationTokenType_forceint = new Discord_AuthorizationTokenType("Discord_AuthorizationTokenType_forceint", discordJNI.Discord_AuthorizationTokenType_forceint_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static Discord_AuthorizationTokenType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + Discord_AuthorizationTokenType.class + " with value " + swigValue);
  }

  private Discord_AuthorizationTokenType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private Discord_AuthorizationTokenType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private Discord_AuthorizationTokenType(String swigName, Discord_AuthorizationTokenType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static Discord_AuthorizationTokenType[] swigValues = { Discord_AuthorizationTokenType_User, Discord_AuthorizationTokenType_Bearer, Discord_AuthorizationTokenType_forceint };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

