// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * void (*Discord_Call_OnParticipantChanged)(unsigned long long userId,_Bool added,void* userData);
 * }
 */
public interface Discord_Call_OnParticipantChanged {

    void apply(long userId, boolean isDiscordRelationshipUpdate, java.lang.foreign.MemorySegment userData);
    static MemorySegment allocate(Discord_Call_OnParticipantChanged fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$11.const$4, fi, constants$11.const$3, scope);
    }
    static Discord_Call_OnParticipantChanged ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (long _userId, boolean _isDiscordRelationshipUpdate, java.lang.foreign.MemorySegment _userData) -> {
            try {
                constants$11.const$5.invokeExact(symbol, _userId, _isDiscordRelationshipUpdate, _userData);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


