// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * void (*Discord_Client_ActivityJoinCallback)(struct Discord_String joinSecret,void* userData);
 * }
 */
public interface Discord_Client_ActivityJoinCallback {

    void apply(java.lang.foreign.MemorySegment joinSecret, java.lang.foreign.MemorySegment userData);
    static MemorySegment allocate(Discord_Client_ActivityJoinCallback fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$28.const$0, fi, constants$27.const$5, scope);
    }
    static Discord_Client_ActivityJoinCallback ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment _joinSecret, java.lang.foreign.MemorySegment _userData) -> {
            try {
                constants$28.const$1.invokeExact(symbol, _joinSecret, _userData);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


