// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * void (*Discord_Client_UserMessageSummariesCallback)(struct Discord_ClientResult* result,struct Discord_UserMessageSummarySpan summaries,void* userData);
 * }
 */
public interface Discord_Client_UserMessageSummariesCallback {

    void apply(java.lang.foreign.MemorySegment result, java.lang.foreign.MemorySegment summaries, java.lang.foreign.MemorySegment userData);
    static MemorySegment allocate(Discord_Client_UserMessageSummariesCallback fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$21.const$2, fi, constants$21.const$1, scope);
    }
    static Discord_Client_UserMessageSummariesCallback ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment _result, java.lang.foreign.MemorySegment _summaries, java.lang.foreign.MemorySegment _userData) -> {
            try {
                constants$21.const$3.invokeExact(symbol, _result, _summaries, _userData);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


