/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.frostclient.discord;

public final class Discord_RelationshipType {
  public final static Discord_RelationshipType Discord_RelationshipType_None = new Discord_RelationshipType("Discord_RelationshipType_None", discordJNI.Discord_RelationshipType_None_get());
  public final static Discord_RelationshipType Discord_RelationshipType_Friend = new Discord_RelationshipType("Discord_RelationshipType_Friend", discordJNI.Discord_RelationshipType_Friend_get());
  public final static Discord_RelationshipType Discord_RelationshipType_Blocked = new Discord_RelationshipType("Discord_RelationshipType_Blocked", discordJNI.Discord_RelationshipType_Blocked_get());
  public final static Discord_RelationshipType Discord_RelationshipType_PendingIncoming = new Discord_RelationshipType("Discord_RelationshipType_PendingIncoming", discordJNI.Discord_RelationshipType_PendingIncoming_get());
  public final static Discord_RelationshipType Discord_RelationshipType_PendingOutgoing = new Discord_RelationshipType("Discord_RelationshipType_PendingOutgoing", discordJNI.Discord_RelationshipType_PendingOutgoing_get());
  public final static Discord_RelationshipType Discord_RelationshipType_Implicit = new Discord_RelationshipType("Discord_RelationshipType_Implicit", discordJNI.Discord_RelationshipType_Implicit_get());
  public final static Discord_RelationshipType Discord_RelationshipType_Suggestion = new Discord_RelationshipType("Discord_RelationshipType_Suggestion", discordJNI.Discord_RelationshipType_Suggestion_get());
  public final static Discord_RelationshipType Discord_RelationshipType_forceint = new Discord_RelationshipType("Discord_RelationshipType_forceint", discordJNI.Discord_RelationshipType_forceint_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static Discord_RelationshipType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + Discord_RelationshipType.class + " with value " + swigValue);
  }

  private Discord_RelationshipType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private Discord_RelationshipType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private Discord_RelationshipType(String swigName, Discord_RelationshipType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static Discord_RelationshipType[] swigValues = { Discord_RelationshipType_None, Discord_RelationshipType_Friend, Discord_RelationshipType_Blocked, Discord_RelationshipType_PendingIncoming, Discord_RelationshipType_PendingOutgoing, Discord_RelationshipType_Implicit, Discord_RelationshipType_Suggestion, Discord_RelationshipType_forceint };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

