/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.frostclient.discord;

public final class Discord_Client_Error {
  public final static Discord_Client_Error Discord_Client_Error_None = new Discord_Client_Error("Discord_Client_Error_None", discordJNI.Discord_Client_Error_None_get());
  public final static Discord_Client_Error Discord_Client_Error_ConnectionFailed = new Discord_Client_Error("Discord_Client_Error_ConnectionFailed", discordJNI.Discord_Client_Error_ConnectionFailed_get());
  public final static Discord_Client_Error Discord_Client_Error_UnexpectedClose = new Discord_Client_Error("Discord_Client_Error_UnexpectedClose", discordJNI.Discord_Client_Error_UnexpectedClose_get());
  public final static Discord_Client_Error Discord_Client_Error_ConnectionCanceled = new Discord_Client_Error("Discord_Client_Error_ConnectionCanceled", discordJNI.Discord_Client_Error_ConnectionCanceled_get());
  public final static Discord_Client_Error Discord_Client_Error_forceint = new Discord_Client_Error("Discord_Client_Error_forceint", discordJNI.Discord_Client_Error_forceint_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static Discord_Client_Error swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + Discord_Client_Error.class + " with value " + swigValue);
  }

  private Discord_Client_Error(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private Discord_Client_Error(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private Discord_Client_Error(String swigName, Discord_Client_Error swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static Discord_Client_Error[] swigValues = { Discord_Client_Error_None, Discord_Client_Error_ConnectionFailed, Discord_Client_Error_UnexpectedClose, Discord_Client_Error_ConnectionCanceled, Discord_Client_Error_forceint };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

