/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.frostclient.discord;

public final class Discord_RelationshipGroupType {
  public final static Discord_RelationshipGroupType Discord_RelationshipGroupType_OnlinePlayingGame = new Discord_RelationshipGroupType("Discord_RelationshipGroupType_OnlinePlayingGame", discordJNI.Discord_RelationshipGroupType_OnlinePlayingGame_get());
  public final static Discord_RelationshipGroupType Discord_RelationshipGroupType_OnlineElsewhere = new Discord_RelationshipGroupType("Discord_RelationshipGroupType_OnlineElsewhere", discordJNI.Discord_RelationshipGroupType_OnlineElsewhere_get());
  public final static Discord_RelationshipGroupType Discord_RelationshipGroupType_Offline = new Discord_RelationshipGroupType("Discord_RelationshipGroupType_Offline", discordJNI.Discord_RelationshipGroupType_Offline_get());
  public final static Discord_RelationshipGroupType Discord_RelationshipGroupType_forceint = new Discord_RelationshipGroupType("Discord_RelationshipGroupType_forceint", discordJNI.Discord_RelationshipGroupType_forceint_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static Discord_RelationshipGroupType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + Discord_RelationshipGroupType.class + " with value " + swigValue);
  }

  private Discord_RelationshipGroupType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private Discord_RelationshipGroupType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private Discord_RelationshipGroupType(String swigName, Discord_RelationshipGroupType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static Discord_RelationshipGroupType[] swigValues = { Discord_RelationshipGroupType_OnlinePlayingGame, Discord_RelationshipGroupType_OnlineElsewhere, Discord_RelationshipGroupType_Offline, Discord_RelationshipGroupType_forceint };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

