/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.frostclient.discord;

public final class Discord_AdditionalContentType {
  public final static Discord_AdditionalContentType Discord_AdditionalContentType_Other = new Discord_AdditionalContentType("Discord_AdditionalContentType_Other", discordJNI.Discord_AdditionalContentType_Other_get());
  public final static Discord_AdditionalContentType Discord_AdditionalContentType_Attachment = new Discord_AdditionalContentType("Discord_AdditionalContentType_Attachment", discordJNI.Discord_AdditionalContentType_Attachment_get());
  public final static Discord_AdditionalContentType Discord_AdditionalContentType_Poll = new Discord_AdditionalContentType("Discord_AdditionalContentType_Poll", discordJNI.Discord_AdditionalContentType_Poll_get());
  public final static Discord_AdditionalContentType Discord_AdditionalContentType_VoiceMessage = new Discord_AdditionalContentType("Discord_AdditionalContentType_VoiceMessage", discordJNI.Discord_AdditionalContentType_VoiceMessage_get());
  public final static Discord_AdditionalContentType Discord_AdditionalContentType_Thread = new Discord_AdditionalContentType("Discord_AdditionalContentType_Thread", discordJNI.Discord_AdditionalContentType_Thread_get());
  public final static Discord_AdditionalContentType Discord_AdditionalContentType_Embed = new Discord_AdditionalContentType("Discord_AdditionalContentType_Embed", discordJNI.Discord_AdditionalContentType_Embed_get());
  public final static Discord_AdditionalContentType Discord_AdditionalContentType_Sticker = new Discord_AdditionalContentType("Discord_AdditionalContentType_Sticker", discordJNI.Discord_AdditionalContentType_Sticker_get());
  public final static Discord_AdditionalContentType Discord_AdditionalContentType_forceint = new Discord_AdditionalContentType("Discord_AdditionalContentType_forceint", discordJNI.Discord_AdditionalContentType_forceint_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static Discord_AdditionalContentType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + Discord_AdditionalContentType.class + " with value " + swigValue);
  }

  private Discord_AdditionalContentType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private Discord_AdditionalContentType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private Discord_AdditionalContentType(String swigName, Discord_AdditionalContentType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static Discord_AdditionalContentType[] swigValues = { Discord_AdditionalContentType_Other, Discord_AdditionalContentType_Attachment, Discord_AdditionalContentType_Poll, Discord_AdditionalContentType_VoiceMessage, Discord_AdditionalContentType_Thread, Discord_AdditionalContentType_Embed, Discord_AdditionalContentType_Sticker, Discord_AdditionalContentType_forceint };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

