/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.frostclient.discord;

public final class Discord_Call_Error {
  public final static Discord_Call_Error Discord_Call_Error_None = new Discord_Call_Error("Discord_Call_Error_None", discordJNI.Discord_Call_Error_None_get());
  public final static Discord_Call_Error Discord_Call_Error_SignalingConnectionFailed = new Discord_Call_Error("Discord_Call_Error_SignalingConnectionFailed", discordJNI.Discord_Call_Error_SignalingConnectionFailed_get());
  public final static Discord_Call_Error Discord_Call_Error_SignalingUnexpectedClose = new Discord_Call_Error("Discord_Call_Error_SignalingUnexpectedClose", discordJNI.Discord_Call_Error_SignalingUnexpectedClose_get());
  public final static Discord_Call_Error Discord_Call_Error_VoiceConnectionFailed = new Discord_Call_Error("Discord_Call_Error_VoiceConnectionFailed", discordJNI.Discord_Call_Error_VoiceConnectionFailed_get());
  public final static Discord_Call_Error Discord_Call_Error_JoinTimeout = new Discord_Call_Error("Discord_Call_Error_JoinTimeout", discordJNI.Discord_Call_Error_JoinTimeout_get());
  public final static Discord_Call_Error Discord_Call_Error_Forbidden = new Discord_Call_Error("Discord_Call_Error_Forbidden", discordJNI.Discord_Call_Error_Forbidden_get());
  public final static Discord_Call_Error Discord_Call_Error_forceint = new Discord_Call_Error("Discord_Call_Error_forceint", discordJNI.Discord_Call_Error_forceint_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static Discord_Call_Error swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + Discord_Call_Error.class + " with value " + swigValue);
  }

  private Discord_Call_Error(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private Discord_Call_Error(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private Discord_Call_Error(String swigName, Discord_Call_Error swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static Discord_Call_Error[] swigValues = { Discord_Call_Error_None, Discord_Call_Error_SignalingConnectionFailed, Discord_Call_Error_SignalingUnexpectedClose, Discord_Call_Error_VoiceConnectionFailed, Discord_Call_Error_JoinTimeout, Discord_Call_Error_Forbidden, Discord_Call_Error_forceint };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

