/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.frostclient.discord;

public final class Discord_AuthenticationExternalAuthType {
  public final static Discord_AuthenticationExternalAuthType Discord_AuthenticationExternalAuthType_OIDC = new Discord_AuthenticationExternalAuthType("Discord_AuthenticationExternalAuthType_OIDC", discordJNI.Discord_AuthenticationExternalAuthType_OIDC_get());
  public final static Discord_AuthenticationExternalAuthType Discord_AuthenticationExternalAuthType_EpicOnlineServicesAccessToken = new Discord_AuthenticationExternalAuthType("Discord_AuthenticationExternalAuthType_EpicOnlineServicesAccessToken", discordJNI.Discord_AuthenticationExternalAuthType_EpicOnlineServicesAccessToken_get());
  public final static Discord_AuthenticationExternalAuthType Discord_AuthenticationExternalAuthType_EpicOnlineServicesIdToken = new Discord_AuthenticationExternalAuthType("Discord_AuthenticationExternalAuthType_EpicOnlineServicesIdToken", discordJNI.Discord_AuthenticationExternalAuthType_EpicOnlineServicesIdToken_get());
  public final static Discord_AuthenticationExternalAuthType Discord_AuthenticationExternalAuthType_SteamSessionTicket = new Discord_AuthenticationExternalAuthType("Discord_AuthenticationExternalAuthType_SteamSessionTicket", discordJNI.Discord_AuthenticationExternalAuthType_SteamSessionTicket_get());
  public final static Discord_AuthenticationExternalAuthType Discord_AuthenticationExternalAuthType_UnityServicesIdToken = new Discord_AuthenticationExternalAuthType("Discord_AuthenticationExternalAuthType_UnityServicesIdToken", discordJNI.Discord_AuthenticationExternalAuthType_UnityServicesIdToken_get());
  public final static Discord_AuthenticationExternalAuthType Discord_AuthenticationExternalAuthType_DiscordBotIssuedAccessToken = new Discord_AuthenticationExternalAuthType("Discord_AuthenticationExternalAuthType_DiscordBotIssuedAccessToken", discordJNI.Discord_AuthenticationExternalAuthType_DiscordBotIssuedAccessToken_get());
  public final static Discord_AuthenticationExternalAuthType Discord_AuthenticationExternalAuthType_AppleIdToken = new Discord_AuthenticationExternalAuthType("Discord_AuthenticationExternalAuthType_AppleIdToken", discordJNI.Discord_AuthenticationExternalAuthType_AppleIdToken_get());
  public final static Discord_AuthenticationExternalAuthType Discord_AuthenticationExternalAuthType_PlayStationNetworkIdToken = new Discord_AuthenticationExternalAuthType("Discord_AuthenticationExternalAuthType_PlayStationNetworkIdToken", discordJNI.Discord_AuthenticationExternalAuthType_PlayStationNetworkIdToken_get());
  public final static Discord_AuthenticationExternalAuthType Discord_AuthenticationExternalAuthType_forceint = new Discord_AuthenticationExternalAuthType("Discord_AuthenticationExternalAuthType_forceint", discordJNI.Discord_AuthenticationExternalAuthType_forceint_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static Discord_AuthenticationExternalAuthType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + Discord_AuthenticationExternalAuthType.class + " with value " + swigValue);
  }

  private Discord_AuthenticationExternalAuthType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private Discord_AuthenticationExternalAuthType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private Discord_AuthenticationExternalAuthType(String swigName, Discord_AuthenticationExternalAuthType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static Discord_AuthenticationExternalAuthType[] swigValues = { Discord_AuthenticationExternalAuthType_OIDC, Discord_AuthenticationExternalAuthType_EpicOnlineServicesAccessToken, Discord_AuthenticationExternalAuthType_EpicOnlineServicesIdToken, Discord_AuthenticationExternalAuthType_SteamSessionTicket, Discord_AuthenticationExternalAuthType_UnityServicesIdToken, Discord_AuthenticationExternalAuthType_DiscordBotIssuedAccessToken, Discord_AuthenticationExternalAuthType_AppleIdToken, Discord_AuthenticationExternalAuthType_PlayStationNetworkIdToken, Discord_AuthenticationExternalAuthType_forceint };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

