/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.frostclient.discord;

public final class Discord_ActivityActionTypes {
  public final static Discord_ActivityActionTypes Discord_ActivityActionTypes_Invalid = new Discord_ActivityActionTypes("Discord_ActivityActionTypes_Invalid", discordJNI.Discord_ActivityActionTypes_Invalid_get());
  public final static Discord_ActivityActionTypes Discord_ActivityActionTypes_Join = new Discord_ActivityActionTypes("Discord_ActivityActionTypes_Join", discordJNI.Discord_ActivityActionTypes_Join_get());
  public final static Discord_ActivityActionTypes Discord_ActivityActionTypes_JoinRequest = new Discord_ActivityActionTypes("Discord_ActivityActionTypes_JoinRequest", discordJNI.Discord_ActivityActionTypes_JoinRequest_get());
  public final static Discord_ActivityActionTypes Discord_ActivityActionTypes_forceint = new Discord_ActivityActionTypes("Discord_ActivityActionTypes_forceint", discordJNI.Discord_ActivityActionTypes_forceint_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static Discord_ActivityActionTypes swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + Discord_ActivityActionTypes.class + " with value " + swigValue);
  }

  private Discord_ActivityActionTypes(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private Discord_ActivityActionTypes(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private Discord_ActivityActionTypes(String swigName, Discord_ActivityActionTypes swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static Discord_ActivityActionTypes[] swigValues = { Discord_ActivityActionTypes_Invalid, Discord_ActivityActionTypes_Join, Discord_ActivityActionTypes_JoinRequest, Discord_ActivityActionTypes_forceint };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

