/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.frostclient.discord;

public final class Discord_UserHandle_AvatarType {
  public final static Discord_UserHandle_AvatarType Discord_UserHandle_AvatarType_Gif = new Discord_UserHandle_AvatarType("Discord_UserHandle_AvatarType_Gif", discordJNI.Discord_UserHandle_AvatarType_Gif_get());
  public final static Discord_UserHandle_AvatarType Discord_UserHandle_AvatarType_Webp = new Discord_UserHandle_AvatarType("Discord_UserHandle_AvatarType_Webp", discordJNI.Discord_UserHandle_AvatarType_Webp_get());
  public final static Discord_UserHandle_AvatarType Discord_UserHandle_AvatarType_Png = new Discord_UserHandle_AvatarType("Discord_UserHandle_AvatarType_Png", discordJNI.Discord_UserHandle_AvatarType_Png_get());
  public final static Discord_UserHandle_AvatarType Discord_UserHandle_AvatarType_Jpeg = new Discord_UserHandle_AvatarType("Discord_UserHandle_AvatarType_Jpeg", discordJNI.Discord_UserHandle_AvatarType_Jpeg_get());
  public final static Discord_UserHandle_AvatarType Discord_UserHandle_AvatarType_forceint = new Discord_UserHandle_AvatarType("Discord_UserHandle_AvatarType_forceint", discordJNI.Discord_UserHandle_AvatarType_forceint_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static Discord_UserHandle_AvatarType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + Discord_UserHandle_AvatarType.class + " with value " + swigValue);
  }

  private Discord_UserHandle_AvatarType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private Discord_UserHandle_AvatarType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private Discord_UserHandle_AvatarType(String swigName, Discord_UserHandle_AvatarType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static Discord_UserHandle_AvatarType[] swigValues = { Discord_UserHandle_AvatarType_Gif, Discord_UserHandle_AvatarType_Webp, Discord_UserHandle_AvatarType_Png, Discord_UserHandle_AvatarType_Jpeg, Discord_UserHandle_AvatarType_forceint };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

