// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * void (*Discord_Client_UserAudioReceivedCallback)(unsigned long long userId,short* data,unsigned long long samplesPerChannel,int sampleRate,unsigned long long channels,_Bool* outShouldMute,void* userData);
 * }
 */
public interface Discord_Client_UserAudioReceivedCallback {

    void apply(long userId, java.lang.foreign.MemorySegment data, long samplesPerChannel, int sampleRate, long channels, java.lang.foreign.MemorySegment outShouldMute, java.lang.foreign.MemorySegment userData);
    static MemorySegment allocate(Discord_Client_UserAudioReceivedCallback fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$16.const$2, fi, constants$16.const$1, scope);
    }
    static Discord_Client_UserAudioReceivedCallback ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (long _userId, java.lang.foreign.MemorySegment _data, long _samplesPerChannel, int _sampleRate, long _channels, java.lang.foreign.MemorySegment _outShouldMute, java.lang.foreign.MemorySegment _userData) -> {
            try {
                constants$16.const$3.invokeExact(symbol, _userId, _data, _samplesPerChannel, _sampleRate, _channels, _outShouldMute, _userData);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


