// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * void (*Discord_Client_GetGuildChannelsCallback)(struct Discord_ClientResult* result,struct Discord_GuildChannelSpan guildChannels,void* userData);
 * }
 */
public interface Discord_Client_GetGuildChannelsCallback {

    void apply(java.lang.foreign.MemorySegment result, java.lang.foreign.MemorySegment guildChannels, java.lang.foreign.MemorySegment userData);
    static MemorySegment allocate(Discord_Client_GetGuildChannelsCallback fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$24.const$4, fi, constants$24.const$3, scope);
    }
    static Discord_Client_GetGuildChannelsCallback ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment _result, java.lang.foreign.MemorySegment _guildChannels, java.lang.foreign.MemorySegment _userData) -> {
            try {
                constants$24.const$5.invokeExact(symbol, _result, _guildChannels, _userData);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


