/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.frostclient.discord;

public class Discord_ActivitySecrets {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Discord_ActivitySecrets(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Discord_ActivitySecrets obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(Discord_ActivitySecrets obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        discordJNI.delete_Discord_ActivitySecrets(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setOpaque(SWIGTYPE_p_void value) {
    discordJNI.Discord_ActivitySecrets_opaque_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getOpaque() {
    long cPtr = discordJNI.Discord_ActivitySecrets_opaque_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public Discord_ActivitySecrets() {
    this(discordJNI.new_Discord_ActivitySecrets(), true);
  }

}
