/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.frostclient.discord;

public final class Discord_Client_Status {
  public final static Discord_Client_Status Discord_Client_Status_Disconnected = new Discord_Client_Status("Discord_Client_Status_Disconnected", discordJNI.Discord_Client_Status_Disconnected_get());
  public final static Discord_Client_Status Discord_Client_Status_Connecting = new Discord_Client_Status("Discord_Client_Status_Connecting", discordJNI.Discord_Client_Status_Connecting_get());
  public final static Discord_Client_Status Discord_Client_Status_Connected = new Discord_Client_Status("Discord_Client_Status_Connected", discordJNI.Discord_Client_Status_Connected_get());
  public final static Discord_Client_Status Discord_Client_Status_Ready = new Discord_Client_Status("Discord_Client_Status_Ready", discordJNI.Discord_Client_Status_Ready_get());
  public final static Discord_Client_Status Discord_Client_Status_Reconnecting = new Discord_Client_Status("Discord_Client_Status_Reconnecting", discordJNI.Discord_Client_Status_Reconnecting_get());
  public final static Discord_Client_Status Discord_Client_Status_Disconnecting = new Discord_Client_Status("Discord_Client_Status_Disconnecting", discordJNI.Discord_Client_Status_Disconnecting_get());
  public final static Discord_Client_Status Discord_Client_Status_HttpWait = new Discord_Client_Status("Discord_Client_Status_HttpWait", discordJNI.Discord_Client_Status_HttpWait_get());
  public final static Discord_Client_Status Discord_Client_Status_forceint = new Discord_Client_Status("Discord_Client_Status_forceint", discordJNI.Discord_Client_Status_forceint_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static Discord_Client_Status swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + Discord_Client_Status.class + " with value " + swigValue);
  }

  private Discord_Client_Status(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private Discord_Client_Status(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private Discord_Client_Status(String swigName, Discord_Client_Status swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static Discord_Client_Status[] swigValues = { Discord_Client_Status_Disconnected, Discord_Client_Status_Connecting, Discord_Client_Status_Connected, Discord_Client_Status_Ready, Discord_Client_Status_Reconnecting, Discord_Client_Status_Disconnecting, Discord_Client_Status_HttpWait, Discord_Client_Status_forceint };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

