// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * void (*Discord_Client_UserMessagesWithLimitCallback)(struct Discord_ClientResult* result,struct Discord_MessageHandleSpan messages,void* userData);
 * }
 */
public interface Discord_Client_UserMessagesWithLimitCallback {

    void apply(java.lang.foreign.MemorySegment result, java.lang.foreign.MemorySegment messages, java.lang.foreign.MemorySegment userData);
    static MemorySegment allocate(Discord_Client_UserMessagesWithLimitCallback fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$21.const$4, fi, constants$20.const$4, scope);
    }
    static Discord_Client_UserMessagesWithLimitCallback ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment _result, java.lang.foreign.MemorySegment _messages, java.lang.foreign.MemorySegment _userData) -> {
            try {
                constants$21.const$0.invokeExact(symbol, _result, _messages, _userData);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


