// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct Discord_Properties {
 *     size_t size;
 *     struct Discord_String* keys;
 *     struct Discord_String* values;
 * };
 * }
 */
public class Discord_Properties {

    public static MemoryLayout $LAYOUT() {
        return constants$1.const$3;
    }
    public static VarHandle size$VH() {
        return constants$1.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * size_t size;
     * }
     */
    public static long size$get(MemorySegment seg) {
        return (long)constants$1.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * size_t size;
     * }
     */
    public static void size$set(MemorySegment seg, long x) {
        constants$1.const$4.set(seg, x);
    }
    public static long size$get(MemorySegment seg, long index) {
        return (long)constants$1.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void size$set(MemorySegment seg, long index, long x) {
        constants$1.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle keys$VH() {
        return constants$1.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * struct Discord_String* keys;
     * }
     */
    public static MemorySegment keys$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$1.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * struct Discord_String* keys;
     * }
     */
    public static void keys$set(MemorySegment seg, MemorySegment x) {
        constants$1.const$5.set(seg, x);
    }
    public static MemorySegment keys$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$1.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void keys$set(MemorySegment seg, long index, MemorySegment x) {
        constants$1.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle values$VH() {
        return constants$2.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * struct Discord_String* values;
     * }
     */
    public static MemorySegment values$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$2.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * struct Discord_String* values;
     * }
     */
    public static void values$set(MemorySegment seg, MemorySegment x) {
        constants$2.const$0.set(seg, x);
    }
    public static MemorySegment values$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$2.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void values$set(MemorySegment seg, long index, MemorySegment x) {
        constants$2.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


