/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.frostclient.discord;

public class Discord_CallSpan {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Discord_CallSpan(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Discord_CallSpan obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(Discord_CallSpan obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        discordJNI.delete_Discord_CallSpan(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPtr(Discord_Call value) {
    discordJNI.Discord_CallSpan_ptr_set(swigCPtr, this, Discord_Call.getCPtr(value), value);
  }

  public Discord_Call getPtr() {
    long cPtr = discordJNI.Discord_CallSpan_ptr_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Discord_Call(cPtr, false);
  }

  public void setSize(long value) {
    discordJNI.Discord_CallSpan_size_set(swigCPtr, this, value);
  }

  public long getSize() {
    return discordJNI.Discord_CallSpan_size_get(swigCPtr, this);
  }

  public Discord_CallSpan() {
    this(discordJNI.new_Discord_CallSpan(), true);
  }

}
