// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * void (*Discord_Client_SendUserMessageCallback)(struct Discord_ClientResult* result,unsigned long long messageId,void* userData);
 * }
 */
public interface Discord_Client_SendUserMessageCallback {

    void apply(java.lang.foreign.MemorySegment result, long lobbyId, java.lang.foreign.MemorySegment userData);
    static MemorySegment allocate(Discord_Client_SendUserMessageCallback fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$22.const$2, fi, constants$22.const$1, scope);
    }
    static Discord_Client_SendUserMessageCallback ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment _result, long _lobbyId, java.lang.foreign.MemorySegment _userData) -> {
            try {
                constants$22.const$3.invokeExact(symbol, _result, _lobbyId, _userData);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


