// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * void (*Discord_Client_UserAudioCapturedCallback)(short* data,unsigned long long samplesPerChannel,int sampleRate,unsigned long long channels,void* userData);
 * }
 */
public interface Discord_Client_UserAudioCapturedCallback {

    void apply(java.lang.foreign.MemorySegment data, long samplesPerChannel, int sampleRate, long channels, java.lang.foreign.MemorySegment userData);
    static MemorySegment allocate(Discord_Client_UserAudioCapturedCallback fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$16.const$5, fi, constants$16.const$4, scope);
    }
    static Discord_Client_UserAudioCapturedCallback ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment _data, long _samplesPerChannel, int _sampleRate, long _channels, java.lang.foreign.MemorySegment _userData) -> {
            try {
                constants$17.const$0.invokeExact(symbol, _data, _samplesPerChannel, _sampleRate, _channels, _userData);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


