/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.frostclient.discord;

public final class Discord_ErrorType {
  public final static Discord_ErrorType Discord_ErrorType_None = new Discord_ErrorType("Discord_ErrorType_None", discordJNI.Discord_ErrorType_None_get());
  public final static Discord_ErrorType Discord_ErrorType_NetworkError = new Discord_ErrorType("Discord_ErrorType_NetworkError", discordJNI.Discord_ErrorType_NetworkError_get());
  public final static Discord_ErrorType Discord_ErrorType_HTTPError = new Discord_ErrorType("Discord_ErrorType_HTTPError", discordJNI.Discord_ErrorType_HTTPError_get());
  public final static Discord_ErrorType Discord_ErrorType_ClientNotReady = new Discord_ErrorType("Discord_ErrorType_ClientNotReady", discordJNI.Discord_ErrorType_ClientNotReady_get());
  public final static Discord_ErrorType Discord_ErrorType_Disabled = new Discord_ErrorType("Discord_ErrorType_Disabled", discordJNI.Discord_ErrorType_Disabled_get());
  public final static Discord_ErrorType Discord_ErrorType_ClientDestroyed = new Discord_ErrorType("Discord_ErrorType_ClientDestroyed", discordJNI.Discord_ErrorType_ClientDestroyed_get());
  public final static Discord_ErrorType Discord_ErrorType_ValidationError = new Discord_ErrorType("Discord_ErrorType_ValidationError", discordJNI.Discord_ErrorType_ValidationError_get());
  public final static Discord_ErrorType Discord_ErrorType_Aborted = new Discord_ErrorType("Discord_ErrorType_Aborted", discordJNI.Discord_ErrorType_Aborted_get());
  public final static Discord_ErrorType Discord_ErrorType_AuthorizationFailed = new Discord_ErrorType("Discord_ErrorType_AuthorizationFailed", discordJNI.Discord_ErrorType_AuthorizationFailed_get());
  public final static Discord_ErrorType Discord_ErrorType_RPCError = new Discord_ErrorType("Discord_ErrorType_RPCError", discordJNI.Discord_ErrorType_RPCError_get());
  public final static Discord_ErrorType Discord_ErrorType_forceint = new Discord_ErrorType("Discord_ErrorType_forceint", discordJNI.Discord_ErrorType_forceint_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static Discord_ErrorType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + Discord_ErrorType.class + " with value " + swigValue);
  }

  private Discord_ErrorType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private Discord_ErrorType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private Discord_ErrorType(String swigName, Discord_ErrorType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static Discord_ErrorType[] swigValues = { Discord_ErrorType_None, Discord_ErrorType_NetworkError, Discord_ErrorType_HTTPError, Discord_ErrorType_ClientNotReady, Discord_ErrorType_Disabled, Discord_ErrorType_ClientDestroyed, Discord_ErrorType_ValidationError, Discord_ErrorType_Aborted, Discord_ErrorType_AuthorizationFailed, Discord_ErrorType_RPCError, Discord_ErrorType_forceint };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

