/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.frostclient.discord;

public final class Discord_AudioModeType {
  public final static Discord_AudioModeType Discord_AudioModeType_MODE_UNINIT = new Discord_AudioModeType("Discord_AudioModeType_MODE_UNINIT", discordJNI.Discord_AudioModeType_MODE_UNINIT_get());
  public final static Discord_AudioModeType Discord_AudioModeType_MODE_VAD = new Discord_AudioModeType("Discord_AudioModeType_MODE_VAD", discordJNI.Discord_AudioModeType_MODE_VAD_get());
  public final static Discord_AudioModeType Discord_AudioModeType_MODE_PTT = new Discord_AudioModeType("Discord_AudioModeType_MODE_PTT", discordJNI.Discord_AudioModeType_MODE_PTT_get());
  public final static Discord_AudioModeType Discord_AudioModeType_forceint = new Discord_AudioModeType("Discord_AudioModeType_forceint", discordJNI.Discord_AudioModeType_forceint_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static Discord_AudioModeType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + Discord_AudioModeType.class + " with value " + swigValue);
  }

  private Discord_AudioModeType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private Discord_AudioModeType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private Discord_AudioModeType(String swigName, Discord_AudioModeType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static Discord_AudioModeType[] swigValues = { Discord_AudioModeType_MODE_UNINIT, Discord_AudioModeType_MODE_VAD, Discord_AudioModeType_MODE_PTT, Discord_AudioModeType_forceint };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

