// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * void (*Discord_Client_FetchCurrentUserCallback)(struct Discord_ClientResult* result,unsigned long long id,struct Discord_String name,void* userData);
 * }
 */
public interface Discord_Client_FetchCurrentUserCallback {

    void apply(java.lang.foreign.MemorySegment result, long id, java.lang.foreign.MemorySegment name, java.lang.foreign.MemorySegment userData);
    static MemorySegment allocate(Discord_Client_FetchCurrentUserCallback fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$18.const$2, fi, constants$18.const$1, scope);
    }
    static Discord_Client_FetchCurrentUserCallback ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment _result, long _id, java.lang.foreign.MemorySegment _name, java.lang.foreign.MemorySegment _userData) -> {
            try {
                constants$18.const$3.invokeExact(symbol, _result, _id, _name, _userData);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


