// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * void (*Discord_Client_JoinLinkedLobbyGuildCallback)(struct Discord_ClientResult* result,struct Discord_String inviteUrl,void* userData);
 * }
 */
public interface Discord_Client_JoinLinkedLobbyGuildCallback {

    void apply(java.lang.foreign.MemorySegment result, java.lang.foreign.MemorySegment joinSecret, java.lang.foreign.MemorySegment userData);
    static MemorySegment allocate(Discord_Client_JoinLinkedLobbyGuildCallback fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$25.const$4, fi, constants$25.const$3, scope);
    }
    static Discord_Client_JoinLinkedLobbyGuildCallback ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment _result, java.lang.foreign.MemorySegment _joinSecret, java.lang.foreign.MemorySegment _userData) -> {
            try {
                constants$25.const$5.invokeExact(symbol, _result, _joinSecret, _userData);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


