// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * void (*Discord_Client_OnStatusChanged)(enum Discord_Client_Status status,enum Discord_Client_Error error,int errorDetail,void* userData);
 * }
 */
public interface Discord_Client_OnStatusChanged {

    void apply(int status, int error, int errorDetail, java.lang.foreign.MemorySegment userData);
    static MemorySegment allocate(Discord_Client_OnStatusChanged fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$24.const$1, fi, constants$12.const$1, scope);
    }
    static Discord_Client_OnStatusChanged ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (int _status, int _error, int _errorDetail, java.lang.foreign.MemorySegment _userData) -> {
            try {
                constants$12.const$3.invokeExact(symbol, _status, _error, _errorDetail, _userData);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


