// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * void (*Discord_Client_LogCallback)(struct Discord_String message,enum Discord_LoggingSeverity severity,void* userData);
 * }
 */
public interface Discord_Client_LogCallback {

    void apply(java.lang.foreign.MemorySegment message, int severity, java.lang.foreign.MemorySegment userData);
    static MemorySegment allocate(Discord_Client_LogCallback fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$23.const$4, fi, constants$23.const$3, scope);
    }
    static Discord_Client_LogCallback ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment _message, int _severity, java.lang.foreign.MemorySegment _userData) -> {
            try {
                constants$23.const$5.invokeExact(symbol, _message, _severity, _userData);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


