/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.frostclient.discord;

public final class Discord_AudioSystem {
  public final static Discord_AudioSystem Discord_AudioSystem_Standard = new Discord_AudioSystem("Discord_AudioSystem_Standard", discordJNI.Discord_AudioSystem_Standard_get());
  public final static Discord_AudioSystem Discord_AudioSystem_Game = new Discord_AudioSystem("Discord_AudioSystem_Game", discordJNI.Discord_AudioSystem_Game_get());
  public final static Discord_AudioSystem Discord_AudioSystem_forceint = new Discord_AudioSystem("Discord_AudioSystem_forceint", discordJNI.Discord_AudioSystem_forceint_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static Discord_AudioSystem swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + Discord_AudioSystem.class + " with value " + swigValue);
  }

  private Discord_AudioSystem(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private Discord_AudioSystem(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private Discord_AudioSystem(String swigName, Discord_AudioSystem swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static Discord_AudioSystem[] swigValues = { Discord_AudioSystem_Standard, Discord_AudioSystem_Game, Discord_AudioSystem_forceint };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

