/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.frostclient.discord;

public final class Discord_StatusDisplayTypes {
  public final static Discord_StatusDisplayTypes Discord_StatusDisplayTypes_Name = new Discord_StatusDisplayTypes("Discord_StatusDisplayTypes_Name", discordJNI.Discord_StatusDisplayTypes_Name_get());
  public final static Discord_StatusDisplayTypes Discord_StatusDisplayTypes_State = new Discord_StatusDisplayTypes("Discord_StatusDisplayTypes_State", discordJNI.Discord_StatusDisplayTypes_State_get());
  public final static Discord_StatusDisplayTypes Discord_StatusDisplayTypes_Details = new Discord_StatusDisplayTypes("Discord_StatusDisplayTypes_Details", discordJNI.Discord_StatusDisplayTypes_Details_get());
  public final static Discord_StatusDisplayTypes Discord_StatusDisplayTypes_forceint = new Discord_StatusDisplayTypes("Discord_StatusDisplayTypes_forceint", discordJNI.Discord_StatusDisplayTypes_forceint_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static Discord_StatusDisplayTypes swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + Discord_StatusDisplayTypes.class + " with value " + swigValue);
  }

  private Discord_StatusDisplayTypes(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private Discord_StatusDisplayTypes(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private Discord_StatusDisplayTypes(String swigName, Discord_StatusDisplayTypes swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static Discord_StatusDisplayTypes[] swigValues = { Discord_StatusDisplayTypes_Name, Discord_StatusDisplayTypes_State, Discord_StatusDisplayTypes_Details, Discord_StatusDisplayTypes_forceint };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

