// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * void (*Discord_Client_LobbyMemberAddedCallback)(unsigned long long lobbyId,unsigned long long memberId,void* userData);
 * }
 */
public interface Discord_Client_LobbyMemberAddedCallback {

    void apply(long lobbyId, long memberId, java.lang.foreign.MemorySegment userData);
    static MemorySegment allocate(Discord_Client_LobbyMemberAddedCallback fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$26.const$4, fi, constants$22.const$5, scope);
    }
    static Discord_Client_LobbyMemberAddedCallback ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (long _lobbyId, long _memberId, java.lang.foreign.MemorySegment _userData) -> {
            try {
                constants$23.const$1.invokeExact(symbol, _lobbyId, _memberId, _userData);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


