/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.frostclient.discord;

public final class Discord_DisclosureTypes {
  public final static Discord_DisclosureTypes Discord_DisclosureTypes_MessageDataVisibleOnDiscord = new Discord_DisclosureTypes("Discord_DisclosureTypes_MessageDataVisibleOnDiscord", discordJNI.Discord_DisclosureTypes_MessageDataVisibleOnDiscord_get());
  public final static Discord_DisclosureTypes Discord_DisclosureTypes_forceint = new Discord_DisclosureTypes("Discord_DisclosureTypes_forceint", discordJNI.Discord_DisclosureTypes_forceint_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static Discord_DisclosureTypes swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + Discord_DisclosureTypes.class + " with value " + swigValue);
  }

  private Discord_DisclosureTypes(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private Discord_DisclosureTypes(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private Discord_DisclosureTypes(String swigName, Discord_DisclosureTypes swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static Discord_DisclosureTypes[] swigValues = { Discord_DisclosureTypes_MessageDataVisibleOnDiscord, Discord_DisclosureTypes_forceint };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

