// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * void (*Discord_Client_GetInputDevicesCallback)(struct Discord_AudioDeviceSpan devices,void* userData);
 * }
 */
public interface Discord_Client_GetInputDevicesCallback {

    void apply(java.lang.foreign.MemorySegment devices, java.lang.foreign.MemorySegment userData);
    static MemorySegment allocate(Discord_Client_GetInputDevicesCallback fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$13.const$5, fi, constants$13.const$4, scope);
    }
    static Discord_Client_GetInputDevicesCallback ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment _devices, java.lang.foreign.MemorySegment _userData) -> {
            try {
                constants$14.const$0.invokeExact(symbol, _devices, _userData);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


