// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * void (*Discord_Client_ExchangeChildTokenCallback)(struct Discord_ClientResult* result,struct Discord_String accessToken,enum Discord_AuthorizationTokenType tokenType,int expiresIn,struct Discord_String scopes,void* userData);
 * }
 */
public interface Discord_Client_ExchangeChildTokenCallback {

    void apply(java.lang.foreign.MemorySegment result, java.lang.foreign.MemorySegment accessToken, int tokenType, int expiresIn, java.lang.foreign.MemorySegment scopes, java.lang.foreign.MemorySegment userData);
    static MemorySegment allocate(Discord_Client_ExchangeChildTokenCallback fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$17.const$5, fi, constants$17.const$4, scope);
    }
    static Discord_Client_ExchangeChildTokenCallback ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment _result, java.lang.foreign.MemorySegment _accessToken, int _tokenType, int _expiresIn, java.lang.foreign.MemorySegment _scopes, java.lang.foreign.MemorySegment _userData) -> {
            try {
                constants$18.const$0.invokeExact(symbol, _result, _accessToken, _tokenType, _expiresIn, _scopes, _userData);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


