/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.frostclient.discord;

public final class Discord_StatusType {
  public final static Discord_StatusType Discord_StatusType_Online = new Discord_StatusType("Discord_StatusType_Online", discordJNI.Discord_StatusType_Online_get());
  public final static Discord_StatusType Discord_StatusType_Offline = new Discord_StatusType("Discord_StatusType_Offline", discordJNI.Discord_StatusType_Offline_get());
  public final static Discord_StatusType Discord_StatusType_Blocked = new Discord_StatusType("Discord_StatusType_Blocked", discordJNI.Discord_StatusType_Blocked_get());
  public final static Discord_StatusType Discord_StatusType_Idle = new Discord_StatusType("Discord_StatusType_Idle", discordJNI.Discord_StatusType_Idle_get());
  public final static Discord_StatusType Discord_StatusType_Dnd = new Discord_StatusType("Discord_StatusType_Dnd", discordJNI.Discord_StatusType_Dnd_get());
  public final static Discord_StatusType Discord_StatusType_Invisible = new Discord_StatusType("Discord_StatusType_Invisible", discordJNI.Discord_StatusType_Invisible_get());
  public final static Discord_StatusType Discord_StatusType_Streaming = new Discord_StatusType("Discord_StatusType_Streaming", discordJNI.Discord_StatusType_Streaming_get());
  public final static Discord_StatusType Discord_StatusType_Unknown = new Discord_StatusType("Discord_StatusType_Unknown", discordJNI.Discord_StatusType_Unknown_get());
  public final static Discord_StatusType Discord_StatusType_forceint = new Discord_StatusType("Discord_StatusType_forceint", discordJNI.Discord_StatusType_forceint_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static Discord_StatusType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + Discord_StatusType.class + " with value " + swigValue);
  }

  private Discord_StatusType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private Discord_StatusType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private Discord_StatusType(String swigName, Discord_StatusType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static Discord_StatusType[] swigValues = { Discord_StatusType_Online, Discord_StatusType_Offline, Discord_StatusType_Blocked, Discord_StatusType_Idle, Discord_StatusType_Dnd, Discord_StatusType_Invisible, Discord_StatusType_Streaming, Discord_StatusType_Unknown, Discord_StatusType_forceint };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

