/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.frostclient.discord;

public final class Discord_ActivityTypes {
  public final static Discord_ActivityTypes Discord_ActivityTypes_Playing = new Discord_ActivityTypes("Discord_ActivityTypes_Playing", discordJNI.Discord_ActivityTypes_Playing_get());
  public final static Discord_ActivityTypes Discord_ActivityTypes_Streaming = new Discord_ActivityTypes("Discord_ActivityTypes_Streaming", discordJNI.Discord_ActivityTypes_Streaming_get());
  public final static Discord_ActivityTypes Discord_ActivityTypes_Listening = new Discord_ActivityTypes("Discord_ActivityTypes_Listening", discordJNI.Discord_ActivityTypes_Listening_get());
  public final static Discord_ActivityTypes Discord_ActivityTypes_Watching = new Discord_ActivityTypes("Discord_ActivityTypes_Watching", discordJNI.Discord_ActivityTypes_Watching_get());
  public final static Discord_ActivityTypes Discord_ActivityTypes_CustomStatus = new Discord_ActivityTypes("Discord_ActivityTypes_CustomStatus", discordJNI.Discord_ActivityTypes_CustomStatus_get());
  public final static Discord_ActivityTypes Discord_ActivityTypes_Competing = new Discord_ActivityTypes("Discord_ActivityTypes_Competing", discordJNI.Discord_ActivityTypes_Competing_get());
  public final static Discord_ActivityTypes Discord_ActivityTypes_HangStatus = new Discord_ActivityTypes("Discord_ActivityTypes_HangStatus", discordJNI.Discord_ActivityTypes_HangStatus_get());
  public final static Discord_ActivityTypes Discord_ActivityTypes_forceint = new Discord_ActivityTypes("Discord_ActivityTypes_forceint", discordJNI.Discord_ActivityTypes_forceint_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static Discord_ActivityTypes swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + Discord_ActivityTypes.class + " with value " + swigValue);
  }

  private Discord_ActivityTypes(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private Discord_ActivityTypes(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private Discord_ActivityTypes(String swigName, Discord_ActivityTypes swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static Discord_ActivityTypes[] swigValues = { Discord_ActivityTypes_Playing, Discord_ActivityTypes_Streaming, Discord_ActivityTypes_Listening, Discord_ActivityTypes_Watching, Discord_ActivityTypes_CustomStatus, Discord_ActivityTypes_Competing, Discord_ActivityTypes_HangStatus, Discord_ActivityTypes_forceint };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

