/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.frostclient.discord;

public final class Discord_ActivityGamePlatforms {
  public final static Discord_ActivityGamePlatforms Discord_ActivityGamePlatforms_Desktop = new Discord_ActivityGamePlatforms("Discord_ActivityGamePlatforms_Desktop", discordJNI.Discord_ActivityGamePlatforms_Desktop_get());
  public final static Discord_ActivityGamePlatforms Discord_ActivityGamePlatforms_Xbox = new Discord_ActivityGamePlatforms("Discord_ActivityGamePlatforms_Xbox", discordJNI.Discord_ActivityGamePlatforms_Xbox_get());
  public final static Discord_ActivityGamePlatforms Discord_ActivityGamePlatforms_Samsung = new Discord_ActivityGamePlatforms("Discord_ActivityGamePlatforms_Samsung", discordJNI.Discord_ActivityGamePlatforms_Samsung_get());
  public final static Discord_ActivityGamePlatforms Discord_ActivityGamePlatforms_IOS = new Discord_ActivityGamePlatforms("Discord_ActivityGamePlatforms_IOS", discordJNI.Discord_ActivityGamePlatforms_IOS_get());
  public final static Discord_ActivityGamePlatforms Discord_ActivityGamePlatforms_Android = new Discord_ActivityGamePlatforms("Discord_ActivityGamePlatforms_Android", discordJNI.Discord_ActivityGamePlatforms_Android_get());
  public final static Discord_ActivityGamePlatforms Discord_ActivityGamePlatforms_Embedded = new Discord_ActivityGamePlatforms("Discord_ActivityGamePlatforms_Embedded", discordJNI.Discord_ActivityGamePlatforms_Embedded_get());
  public final static Discord_ActivityGamePlatforms Discord_ActivityGamePlatforms_PS4 = new Discord_ActivityGamePlatforms("Discord_ActivityGamePlatforms_PS4", discordJNI.Discord_ActivityGamePlatforms_PS4_get());
  public final static Discord_ActivityGamePlatforms Discord_ActivityGamePlatforms_PS5 = new Discord_ActivityGamePlatforms("Discord_ActivityGamePlatforms_PS5", discordJNI.Discord_ActivityGamePlatforms_PS5_get());
  public final static Discord_ActivityGamePlatforms Discord_ActivityGamePlatforms_forceint = new Discord_ActivityGamePlatforms("Discord_ActivityGamePlatforms_forceint", discordJNI.Discord_ActivityGamePlatforms_forceint_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static Discord_ActivityGamePlatforms swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + Discord_ActivityGamePlatforms.class + " with value " + swigValue);
  }

  private Discord_ActivityGamePlatforms(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private Discord_ActivityGamePlatforms(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private Discord_ActivityGamePlatforms(String swigName, Discord_ActivityGamePlatforms swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static Discord_ActivityGamePlatforms[] swigValues = { Discord_ActivityGamePlatforms_Desktop, Discord_ActivityGamePlatforms_Xbox, Discord_ActivityGamePlatforms_Samsung, Discord_ActivityGamePlatforms_IOS, Discord_ActivityGamePlatforms_Android, Discord_ActivityGamePlatforms_Embedded, Discord_ActivityGamePlatforms_PS4, Discord_ActivityGamePlatforms_PS5, Discord_ActivityGamePlatforms_forceint };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

