// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * void (*Discord_Client_DeviceChangeCallback)(struct Discord_AudioDeviceSpan inputDevices,struct Discord_AudioDeviceSpan outputDevices,void* userData);
 * }
 */
public interface Discord_Client_DeviceChangeCallback {

    void apply(java.lang.foreign.MemorySegment inputDevices, java.lang.foreign.MemorySegment outputDevices, java.lang.foreign.MemorySegment userData);
    static MemorySegment allocate(Discord_Client_DeviceChangeCallback fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$14.const$3, fi, constants$14.const$2, scope);
    }
    static Discord_Client_DeviceChangeCallback ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment _inputDevices, java.lang.foreign.MemorySegment _outputDevices, java.lang.foreign.MemorySegment _userData) -> {
            try {
                constants$14.const$4.invokeExact(symbol, _inputDevices, _outputDevices, _userData);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


