/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.frostclient.discord;

public final class Discord_ActivityPartyPrivacy {
  public final static Discord_ActivityPartyPrivacy Discord_ActivityPartyPrivacy_Private = new Discord_ActivityPartyPrivacy("Discord_ActivityPartyPrivacy_Private", discordJNI.Discord_ActivityPartyPrivacy_Private_get());
  public final static Discord_ActivityPartyPrivacy Discord_ActivityPartyPrivacy_Public = new Discord_ActivityPartyPrivacy("Discord_ActivityPartyPrivacy_Public", discordJNI.Discord_ActivityPartyPrivacy_Public_get());
  public final static Discord_ActivityPartyPrivacy Discord_ActivityPartyPrivacy_forceint = new Discord_ActivityPartyPrivacy("Discord_ActivityPartyPrivacy_forceint", discordJNI.Discord_ActivityPartyPrivacy_forceint_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static Discord_ActivityPartyPrivacy swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + Discord_ActivityPartyPrivacy.class + " with value " + swigValue);
  }

  private Discord_ActivityPartyPrivacy(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private Discord_ActivityPartyPrivacy(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private Discord_ActivityPartyPrivacy(String swigName, Discord_ActivityPartyPrivacy swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static Discord_ActivityPartyPrivacy[] swigValues = { Discord_ActivityPartyPrivacy_Private, Discord_ActivityPartyPrivacy_Public, Discord_ActivityPartyPrivacy_forceint };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

