// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * void (*Discord_Client_VoiceParticipantChangedCallback)(unsigned long long lobbyId,unsigned long long memberId,_Bool added,void* userData);
 * }
 */
public interface Discord_Client_VoiceParticipantChangedCallback {

    void apply(long lobbyId, long memberId, boolean added, java.lang.foreign.MemorySegment userData);
    static MemorySegment allocate(Discord_Client_VoiceParticipantChangedCallback fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$15.const$5, fi, constants$15.const$4, scope);
    }
    static Discord_Client_VoiceParticipantChangedCallback ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (long _lobbyId, long _memberId, boolean _added, java.lang.foreign.MemorySegment _userData) -> {
            try {
                constants$16.const$0.invokeExact(symbol, _lobbyId, _memberId, _added, _userData);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


