/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.frostclient.discord;

public final class Discord_ExternalIdentityProviderType {
  public final static Discord_ExternalIdentityProviderType Discord_ExternalIdentityProviderType_OIDC = new Discord_ExternalIdentityProviderType("Discord_ExternalIdentityProviderType_OIDC", discordJNI.Discord_ExternalIdentityProviderType_OIDC_get());
  public final static Discord_ExternalIdentityProviderType Discord_ExternalIdentityProviderType_EpicOnlineServices = new Discord_ExternalIdentityProviderType("Discord_ExternalIdentityProviderType_EpicOnlineServices", discordJNI.Discord_ExternalIdentityProviderType_EpicOnlineServices_get());
  public final static Discord_ExternalIdentityProviderType Discord_ExternalIdentityProviderType_Steam = new Discord_ExternalIdentityProviderType("Discord_ExternalIdentityProviderType_Steam", discordJNI.Discord_ExternalIdentityProviderType_Steam_get());
  public final static Discord_ExternalIdentityProviderType Discord_ExternalIdentityProviderType_Unity = new Discord_ExternalIdentityProviderType("Discord_ExternalIdentityProviderType_Unity", discordJNI.Discord_ExternalIdentityProviderType_Unity_get());
  public final static Discord_ExternalIdentityProviderType Discord_ExternalIdentityProviderType_DiscordBot = new Discord_ExternalIdentityProviderType("Discord_ExternalIdentityProviderType_DiscordBot", discordJNI.Discord_ExternalIdentityProviderType_DiscordBot_get());
  public final static Discord_ExternalIdentityProviderType Discord_ExternalIdentityProviderType_None = new Discord_ExternalIdentityProviderType("Discord_ExternalIdentityProviderType_None", discordJNI.Discord_ExternalIdentityProviderType_None_get());
  public final static Discord_ExternalIdentityProviderType Discord_ExternalIdentityProviderType_Unknown = new Discord_ExternalIdentityProviderType("Discord_ExternalIdentityProviderType_Unknown", discordJNI.Discord_ExternalIdentityProviderType_Unknown_get());
  public final static Discord_ExternalIdentityProviderType Discord_ExternalIdentityProviderType_forceint = new Discord_ExternalIdentityProviderType("Discord_ExternalIdentityProviderType_forceint", discordJNI.Discord_ExternalIdentityProviderType_forceint_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static Discord_ExternalIdentityProviderType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + Discord_ExternalIdentityProviderType.class + " with value " + swigValue);
  }

  private Discord_ExternalIdentityProviderType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private Discord_ExternalIdentityProviderType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private Discord_ExternalIdentityProviderType(String swigName, Discord_ExternalIdentityProviderType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static Discord_ExternalIdentityProviderType[] swigValues = { Discord_ExternalIdentityProviderType_OIDC, Discord_ExternalIdentityProviderType_EpicOnlineServices, Discord_ExternalIdentityProviderType_Steam, Discord_ExternalIdentityProviderType_Unity, Discord_ExternalIdentityProviderType_DiscordBot, Discord_ExternalIdentityProviderType_None, Discord_ExternalIdentityProviderType_Unknown, Discord_ExternalIdentityProviderType_forceint };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

