// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * void* (*Discord_MallocFn)(unsigned long long size);
 * }
 */
public interface Discord_MallocFn {

    java.lang.foreign.MemorySegment apply(long size);
    static MemorySegment allocate(Discord_MallocFn fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$2.const$2, fi, constants$2.const$1, scope);
    }
    static Discord_MallocFn ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (long _size) -> {
            try {
                return (java.lang.foreign.MemorySegment)constants$2.const$3.invokeExact(symbol, _size);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


