/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.frostclient.discord;

public final class Discord_Client_Thread {
  public final static Discord_Client_Thread Discord_Client_Thread_Client = new Discord_Client_Thread("Discord_Client_Thread_Client", discordJNI.Discord_Client_Thread_Client_get());
  public final static Discord_Client_Thread Discord_Client_Thread_Voice = new Discord_Client_Thread("Discord_Client_Thread_Voice", discordJNI.Discord_Client_Thread_Voice_get());
  public final static Discord_Client_Thread Discord_Client_Thread_Network = new Discord_Client_Thread("Discord_Client_Thread_Network", discordJNI.Discord_Client_Thread_Network_get());
  public final static Discord_Client_Thread Discord_Client_Thread_forceint = new Discord_Client_Thread("Discord_Client_Thread_forceint", discordJNI.Discord_Client_Thread_forceint_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static Discord_Client_Thread swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + Discord_Client_Thread.class + " with value " + swigValue);
  }

  private Discord_Client_Thread(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private Discord_Client_Thread(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private Discord_Client_Thread(String swigName, Discord_Client_Thread swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static Discord_Client_Thread[] swigValues = { Discord_Client_Thread_Client, Discord_Client_Thread_Voice, Discord_Client_Thread_Network, Discord_Client_Thread_forceint };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

