/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.frostclient.discord;

public final class Discord_AuthenticationCodeChallengeMethod {
  public final static Discord_AuthenticationCodeChallengeMethod Discord_AuthenticationCodeChallengeMethod_S256 = new Discord_AuthenticationCodeChallengeMethod("Discord_AuthenticationCodeChallengeMethod_S256", discordJNI.Discord_AuthenticationCodeChallengeMethod_S256_get());
  public final static Discord_AuthenticationCodeChallengeMethod Discord_AuthenticationCodeChallengeMethod_forceint = new Discord_AuthenticationCodeChallengeMethod("Discord_AuthenticationCodeChallengeMethod_forceint", discordJNI.Discord_AuthenticationCodeChallengeMethod_forceint_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static Discord_AuthenticationCodeChallengeMethod swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + Discord_AuthenticationCodeChallengeMethod.class + " with value " + swigValue);
  }

  private Discord_AuthenticationCodeChallengeMethod(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private Discord_AuthenticationCodeChallengeMethod(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private Discord_AuthenticationCodeChallengeMethod(String swigName, Discord_AuthenticationCodeChallengeMethod swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static Discord_AuthenticationCodeChallengeMethod[] swigValues = { Discord_AuthenticationCodeChallengeMethod_S256, Discord_AuthenticationCodeChallengeMethod_forceint };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

