/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.frostclient.discord;

public final class Discord_Call_Status {
  public final static Discord_Call_Status Discord_Call_Status_Disconnected = new Discord_Call_Status("Discord_Call_Status_Disconnected", discordJNI.Discord_Call_Status_Disconnected_get());
  public final static Discord_Call_Status Discord_Call_Status_Joining = new Discord_Call_Status("Discord_Call_Status_Joining", discordJNI.Discord_Call_Status_Joining_get());
  public final static Discord_Call_Status Discord_Call_Status_Connecting = new Discord_Call_Status("Discord_Call_Status_Connecting", discordJNI.Discord_Call_Status_Connecting_get());
  public final static Discord_Call_Status Discord_Call_Status_SignalingConnected = new Discord_Call_Status("Discord_Call_Status_SignalingConnected", discordJNI.Discord_Call_Status_SignalingConnected_get());
  public final static Discord_Call_Status Discord_Call_Status_Connected = new Discord_Call_Status("Discord_Call_Status_Connected", discordJNI.Discord_Call_Status_Connected_get());
  public final static Discord_Call_Status Discord_Call_Status_Reconnecting = new Discord_Call_Status("Discord_Call_Status_Reconnecting", discordJNI.Discord_Call_Status_Reconnecting_get());
  public final static Discord_Call_Status Discord_Call_Status_Disconnecting = new Discord_Call_Status("Discord_Call_Status_Disconnecting", discordJNI.Discord_Call_Status_Disconnecting_get());
  public final static Discord_Call_Status Discord_Call_Status_forceint = new Discord_Call_Status("Discord_Call_Status_forceint", discordJNI.Discord_Call_Status_forceint_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static Discord_Call_Status swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + Discord_Call_Status.class + " with value " + swigValue);
  }

  private Discord_Call_Status(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private Discord_Call_Status(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private Discord_Call_Status(String swigName, Discord_Call_Status swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static Discord_Call_Status[] swigValues = { Discord_Call_Status_Disconnected, Discord_Call_Status_Joining, Discord_Call_Status_Connecting, Discord_Call_Status_SignalingConnected, Discord_Call_Status_Connected, Discord_Call_Status_Reconnecting, Discord_Call_Status_Disconnecting, Discord_Call_Status_forceint };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

