// Generated by jextract

package com.frostclient.discord;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * void (*Discord_Client_TokenExpirationCallback)(void* userData);
 * }
 */
public interface Discord_Client_TokenExpirationCallback {

    void apply(java.lang.foreign.MemorySegment userData);
    static MemorySegment allocate(Discord_Client_TokenExpirationCallback fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$19.const$4, fi, constants$0.const$0, scope);
    }
    static Discord_Client_TokenExpirationCallback ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment _userData) -> {
            try {
                constants$2.const$5.invokeExact(symbol, _userData);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


